### ISSUE TITLE
Optimize release

### ISSUE THREAD

**Issue by Mazwak** [ajour/ajour#364]
**Is your feature request related to a problem? Please describe.**
No problem in particular. Would make the binary smaller mainly

**Describe the solution you'd like**
Add a `[profile.release]` tweaked for smaller and ?faster? binary.

The main tweaks are:

- lto = true
- codegen-units = 1
- incremental = false
- opt-level = "z"

On my computer, with sccache.
Current binary is approximately 16.7 MB.
Compiled in 1m53s.

Option | size | Gain % | Time
--------|-----|--------|-----
lto | 14.8 | 11 % | 3m54s
codegen-units | 14.4 | 14 % | 2m26s
incremental | 16.7 | 0 % | 1m52s
opt-level | 12.0 | 28 % | 54s
all | 9.3 | 44 % | 2m30s

Times are to take not too seriously.
LTO has a big impact on the last build (ajour bin).

I think it would be reasonnable to enable all 4.

**Comment by tarkah** [comment]
Awesome stuff! I'd be interested to see the performance gains with LTO. We can also try `lto = "thin"` to see if it has similar gains, as it should reduce compile time some.

**Comment by Mazwak** [comment]
LTO:
https://doc.rust-lang.org/rustc/linker-plugin-lto.html

codegen-units:
https://doc.rust-lang.org/rustc/codegen-options/index.html

incremental:
https://blog.rust-lang.org/2016/09/08/incremental.html
This is the least impactfull imo

opt-level:
https://doc.rust-lang.org/rustc/codegen-options/index.html

generic information:
https://rust-embedded.github.io/book/unsorted/speed-vs-size.html

**Comment by tarkah** [comment]
Isn't incremental already disabled for release builds?

**Comment by Mazwak** [comment]
It is indeed: https://github.com/rust-lang/cargo/pull/4817
