### ISSUE TITLE
Missing localizations

### ISSUE THREAD

**Issue by casperstorm** [ajour/ajour#491]
**Describe the bug**
I version [0.6.2](https://github.com/casperstorm/ajour/releases/tag/0.6.2) we introduced localizations. There are however a few places where we are missing some translations:

- [ ] Addon release channels: `Default`, `Stable`, `Beta `and `Alpha`
- [x] `Results` in Catalog

**Comment by zeeraw** [comment]
@casperstorm Do you think `Default`, `Stable`, `Beta` & `Alpha` should actually be translated since they're named channels that correspond to external sources?

**Comment by casperstorm** [comment]
> @casperstorm Do you think `Default`, `Stable`, `Beta` & `Alpha` should actually be translated since they're named channels that correspond to external sources?

They should be translated eventually but right now they live in another crate which is decoupled from the GUI where we have translation going. So it's not as easy as it sounds

The "Results" string however lives in the GUI (main) crate.
