### ISSUE TITLE
Missing versions 

### ISSUE THREAD

**Issue by SamMousa** [ajour/ajour#507]
I've got the feeling that I'm not getting updates for some addons. Not yet sure how to do more research on why ajour is ignoring a version.

Will add more details later.

**Comment by casperstorm** [comment]
Please use the template when submitting bugs (and features) as it helps us with reproduction.
Could you post ajour.log, fingerprint.yml and which addon isn't getting any updates?

**Comment by SamMousa** [comment]
> Please use the template when submitting bugs

Apologies, apparently my github android app doesn't pick up the issue template!

> Could you post ajour.log, fingerprint.yml and which addon isn't getting any updates?

Yes will do, if there are logs I'll inspect them myself first, as said will add more details when I know more :)

**Comment by SamMousa** [comment]
Closing this, after some more research:
- I was getting out of date message from Details!, but this was probably from someone else running the retail version on their classic wow.
- I had some DBM modules missing but it turns out it was corruption instead of an old version.

**Comment by casperstorm** [comment]
> Closing this, after some more research:
> 
> * I was getting out of date message from Details!, but this was probably from someone else running the retail version on their classic wow.
> * I had some DBM modules missing but it turns out it was corruption instead of an old version.

Glad you sorted it out. :)
