### ISSUE TITLE
Auto user sync

### ISSUE THREAD

**Issue by blaadje** [ajour/ajour#509]
**Describe the solution you'd like**
Hi ! First thank you for your awesome app. Useful, Ergonomic, fast & design 😍 
Now I think a big issue in wow is the syncing between user and addons (addons settings).

A nice thing would be to 
- have ajour accounts 
- link it (connect) somehow with the battle.net account.
- save in user accounts **wtf folder/list of addons to DL by ajour**.
Consequently by changing computer it would take few seconds to retrieve configuration.

Tell me if its relevant/possible/clear.

Cheers !

**Comment by tarkah** [comment]
@blaadje I don't see us supporting accounts for Ajour. One idea that is very similar is having the ability to export / import the list of addons within Ajour. There is a discussion post for this: https://github.com/ajour/ajour/discussions/172. The idea here is you can export your addon list from one computer, and load it from another computer and automatically download all those addons. This would also be handy for "sharing" which addons you use with friends / guildies for them to easily install in one action. This is something on our backlog, but isn't prioritized currently.
