### ISSUE TITLE
Ajour UI is upside down

### ISSUE THREAD

**Issue by Maia-Everett** [ajour/ajour#510]
I've hit a really weird bug. The Ajour UI is displayed upside down on my system.

Windows 10 version 1909, a laptop with NVIDIA GeForce GT 640M LE, driver 368.22.

I'll try updating to Windows 10 version 20H2 and see if it fixes the problem.

![image](https://user-images.githubusercontent.com/10684/105735859-c2891a00-5f66-11eb-94dd-57df83dff291.png)

**Comment by casperstorm** [comment]
Hi @Maia-Everett,
Thats.... a new issue, haha.

Could you try to download the opengl version of Ajour and see if it has same behaviour?

https://www.getajour.com/download

**Comment by Maia-Everett** [comment]
I didn't try the OpenGL version, but I did update to the latest NVIDIA driver version, and that fixed the problem.

You can close the issue if you wish.
