### ISSUE TITLE
TownLong-Yak Addons Repository

### ISSUE THREAD

**Issue by samueldcorbin** [ajour/ajour#512]
The TownLong-Yak addons (OPie, etc.) aren't kept up to date in any of the standard repositories (OPie has been several versions behind for months now, and is missing bug fixes and a lot of Shadowlands functionality).

These addons are quite popular, TownLong-Yak is a pretty established WoW resource, and they ought to be added to Ajour as a repository.

The site has an API to check for updates: https://www.townlong-yak.com/addons/about/update-api

**Comment by StragaSevera** [comment]
It would be awesome to have the ability to update this addons via Ajour!

**Comment by KaspOu** [comment]
I use OPie and Venture Plan, and it would be awesome to add this feature (currently in beta in one concurrent, but I love Ajour).

**Comment by ueberBrot** [comment]
Based on [this thread from the WowUp github page](https://github.com/WowUp/WowUp/issues/620) TownLong-Yak added a public API.
It is implemented for WowUp. You can install all addons from the site with WowUp.
What I found is the following: https://www.townlong-yak.com/addons/about/update-api
I think you can implement it with this information.
I'm looking forward to it 😊.

**Comment by casperstorm** [comment]
This is now available in 0.7.1-rc.1. Make sure you Ajour Update Channel to `beta` and you should be able to update.

**Comment by StragaSevera** [comment]
I'm using the 0.7.1 now, and VenturePlan does not show as an updatable addon:
![image](https://user-images.githubusercontent.com/6378091/108053668-c63c2800-705e-11eb-864e-bb40c850d6e2.png)
Also it does not show in the catalog.

**Comment by casperstorm** [comment]
> I'm using the 0.7.1 now, and VenturePlan does not show as an updatable addon:
> ![image](https://user-images.githubusercontent.com/6378091/108053668-c63c2800-705e-11eb-864e-bb40c850d6e2.png)
> Also it does not show in the catalog, so I can't reinstall it.

You need to delete it, and install it through Ajour catalog before it's able to catch it.
You find it in the catalog if you select `TownlongYak` as source in the top menu.

**Comment by StragaSevera** [comment]
Thank you!
