### ISSUE TITLE
Template in translation should start with a capital letter when at the beginning of a sentence

### ISSUE THREAD

**Issue by krisz094** [ajour/ajour#514]
**Describe the bug**
While testing the Hungarian localization that I made, I noticed that when the app starts up, it uses the message "Currently parsing {flavor} AddOns". Obviously, in English it's something like "Currently parsing retail AddOns", where the word in the middle is lowercase. 

In Hungarian, the sentence starts with the template, like "{flavor} AddOnok beolvasása", so it becomes "retail AddOnok beolvasása" which looks odd.

**To Reproduce**
1. Select Hungarian in Ajour
2. Close the app
3. Open the app

**Expected behavior**
Sentence should start with capital letter.

**Screenshots**
![image](https://user-images.githubusercontent.com/13174664/105862677-5b17ac80-5ff0-11eb-8608-356df9c06a42.png)

**Software involved**
Please complete the following information:
 - OS: Win10
 - Ajour version: 0.7.0

**Comment by casperstorm** [comment]
Thank you for the suggestion. If you are up for it you can help contribute to the strings here: https://poeditor.com/join/project?hash=gjghTR7d0Z
