### ISSUE TITLE
Addons Directory Button

### ISSUE THREAD

**Issue by samueldcorbin** [ajour/ajour#525]
**Is your feature request related to a problem? Please describe.**
If Ajour doesn't support an addon's repository, and I have to add the addon to my addons folder by hand, it's annoying to have to navigate to the addons folder.

**Describe the solution you'd like**
Ajour already knows where the addons folder is, so it's the perfect place to make this easier and put addon management all under one roof. A simple "open addons folder" button would be easy and help cement Ajour as The Program to Open For Managing Your Addons. Then, when I want to add an addon - I open Ajour: either I get it through the catalog, or, if I have to install it manually because the catalog doesn't include it, Ajour makes that easier too.

I would put it next to the About and Settings buttons. So it would look like "About | Addons Folder | Settings".

**Describe alternatives you've considered**
Alternatively, an "add addon file" option could pop open a file dialogue allowing a user to select a zipped file and then Ajour would add it to the addons folder, but I think it would be much better to just give people an easy way to access the folder - even the least capable user can handle dragging a file into there themselves, and there are other reasons one might want to access the addons folder beyond adding things, so a button to open a file browser at the location would be more useful.

Another option would be to add a button to the Settings page: add Open Addons Directory below Select Directory. This might be preferable to keep the interface simple for people intimidated by messing with the files themselves, but would also be harder to find, and it might feel strange to have one way of adding addons in the Settings while the others are in the menu bar.

**Comment by casperstorm** [comment]
I understand the reason for this button, but I think it will be valuable for most users. The reason being that if you decide to manually install a addon, you are likely doing the following:

1. Go to the specific source and find your wanted addon.
2. Download the addon.
3. Open your Download folder and unzip the newly downloaded Addon.
4. Copy the addon.
5. Paste the addon into the addons directory.

I am not sure it will be faster to have a step between **4.** and **5.** where you reopen Ajour and press a button to open the correct directory rather than having your World of Warcraft directory pinned to either Explorer/Finder.

**Comment by samueldcorbin** [comment]
Most users are not going to pin a folder that they have to open once every few months. I bet if you surveyed the users on whether they have the addons folder pinned in explorer, the percentage would be in the single digits. One of the benefits of Ajour is removing the need to interact with the folder in most cases.

Many users, who have only ever used an addon manager, won't even know where the folder is.

Is it possible that your thinking on this is distorted by the fact that, as the author of an addon manager, you are more familiar with the process and end up interacting with the folder more frequently than many users may be?

And what is the cost of adding this convenience? If there is a worry about clutter, going with the Settings page option adds virtually no clutter.

I have also frequently wanted to go to the folder of a particular addon, and was somewhat surprised that wasn't one of the buttons when expanding an add-on - that would also be a potential solution, albeit an indirect one (by going to an addon then up a directory), and there are probably fewer users who want to inspect or modify addon code.
