### ISSUE TITLE
[Feature Request] Ability to blacklist or individually update Weakauras

### ISSUE THREAD

**Issue by Pantar2205** [ajour/ajour#534]
**Is your feature request related to a problem? Please describe.**
I have installed wa's from wago.io and heavily modified them. I never want to "upgrade" these WA's.

**Describe the solution you'd like**
Ideally = Mark a  WA as never to be upgraded to be able to add it to an upgrade blacklist somewhere.
Possible work around = allow to individually upgrade each WA so I can upgrade ones and not others.

**Describe alternatives you've considered**
Manually imporitng for now. If i ever upgraded my WA's it could possible un do months of custom alterations.

**Additional context**
n/a

**Comment by casperstorm** [comment]
You can blacklist individual WeakAuras in the in-game menu.
Since this is something they are handling, I don't think it make sense Ajour implements it as well.
