### ISSUE TITLE
Problems with upgrading Ajour to 0.7.1 under Linux

### ISSUE THREAD

**Issue by StragaSevera** [ajour/ajour#537]
**Describe the bug**
The Ajour is installed from the `cargo` manager, but the published version there is 0.7.0.

When I click the "update" button in Ajour, I receive a message: "Failed to update Ajour".

**Software involved**
 - OS: Arch Linux
 - Ajour version: 0.7.0

**Log Output**
[ajour.log](https://github.com/ajour/ajour/files/5986793/ajour.log)

**Comment by casperstorm** [comment]
I've just updated the crates to `0.7.1`.
We are missing a automated system to do this. Something i'll look into making.

**Comment by tarkah** [comment]
@StragaSevera Yeah, the update button only works for the AppImage version for linux. We should probably add some logic to only show that button if running from the AppImage so it's not confusing for those updating via source / cargo
