### ISSUE TITLE
"Latest Release" filter for the Catalog tab

### ISSUE THREAD

**Issue by Kuurse** [ajour/ajour#541]
**Is your feature request related to a problem? Please describe.**
I would like to be able to add a filter for Latest Release in the Catalog tab so I can hide old unsupported add-ons.

**Describe the solution you'd like**
There is already a "Source", "Category" and "# of results" filter, I would like a similar filter for Latest Release.

**Describe alternatives you've considered**
The filter could also be in the Settings pannel, I don't really care either way.

**Additional context**
/

**Comment by mlablah** [comment]
@casperstorm @tarkah If we start down this path, I think we would have to add a system for optional filters in the Catalog similar to what we have for columns. 

The search bar would get quite crowded if we start adding one or more filters to it:
![image](https://user-images.githubusercontent.com/68285419/108518079-76609980-72c8-11eb-8ae5-b0104d4bb3fe.png)

@NathanCrama As a workaround you can enable the `Latest Release` column for the Catalog inside Settings, and then order the list of results by that column.

**Comment by casperstorm** [comment]
While the Catalog is great and fast for installing addons, it's never been the intention to be a place to go if you are on the lookout for new and addons, without knowing exactly what you want. There are better alternatives for that, with images, videos, and such. I believe, as @mlablah points out, the right solution here is to use our columns to display Game Versions.

Honestly, I am even questioning us having a filter for categories. I don't think it is very used.
