### ISSUE TITLE
Automatic backups

### ISSUE THREAD

**Issue by NathanCrama** [ajour/ajour#543]
**Is your feature request related to a problem? Please describe.**
Ajour already offers a backup option, but it has to be done manually. It would be great to automate the process.

**Describe the solution you'd like**
A configurable and automatic backup when Ajour is opened. It could be configured to be run every X days, with a maximum number of backups that would delete the older ones (eg. backup every 3 days and keep 5 archives maximum).

**Describe alternatives you've considered**

**Additional context**

**Comment by casperstorm** [comment]
We have a [CLI](https://github.com/ajour/ajour/blob/master/CLI.md) where you can actually automate a lot of different aspects of Ajour. Including backup. You can find a few examples in our our [Wiki](https://github.com/ajour/ajour/wiki).

It will quickly become very advanced UI wise to add such automations into the GUI so for now, we will keep it to the CLI.
