### ISSUE TITLE
Ability to view/choose source of addon

### ISSUE THREAD

**Issue by thirdletter** [ajour/ajour#551]
I've run into problems in the past that an addon is available on both curseforge and tukui, but that for example only the tukui source has already updated, and curseforge has not. I currently do not see a way to manually verify/select a source target for the addon to install/update.

**Comment by mlablah** [comment]
@thirdletter If an addon wasn't installed through the Ajour catalog we will try to match it against curseforge and failing that, use other id's in the .toc metadata to identify it. If you want to ensure that a certain source is used, you can install the addon through the catalog using the desired source. Ajour will then save the necessary metadata to always match it against that source and look for new updates there.

If you want to see which source Ajour has matched the addon against, you can enable the optional column `Source` in Settings:
![image](https://user-images.githubusercontent.com/68285419/109148361-79470880-7766-11eb-9bc9-3ed50ca20d9f.png)

It will look something like this:
![image](https://user-images.githubusercontent.com/68285419/109148475-9e3b7b80-7766-11eb-9508-984c14a97284.png)

Does this satisfy your feature request?

**Comment by tarkah** [comment]
@thirdletter We do not support "dynamically" changing which repository an addon links to / gets updates from. As @mlablah mentioned, it's based off which source it was installed on, if installed via our Catalog. If you didn't install it via the catalog, it'll basically try to match to Curse first based on a fingerprint of the addon, then fallback to matching to Curse / Tukui / WowI based on X-Metadata IDs in the .toc file.

So for now, if updates are always hitting Tukui first for a specific addon, our recommendation is to delete it and reinstall it via our Catalog for that source to ensure it links to / fetches updates from it.

**Comment by casperstorm** [comment]
I'll close this for now since it is not in our scope to support dynamically changing source.
