### ISSUE TITLE
Want a button "Redownload" in Catalog.

### ISSUE THREAD

**Issue by kiddingbaby** [ajour/ajour#555]
When failed to download catalog, I really want a button "redownload", instead of waiting "Loading" for a long time.

**Comment by casperstorm** [comment]
I am wondering why the catalog is failing for you in the first place?

**Comment by kiddingbaby** [comment]
I have to use the proxy(shadowsocks) to bypass the firewall. When i visit curseforge.com, i must enter a CAPTCHA to proves i'm not a robot.

**Comment by tarkah** [comment]
Hm, we have logic in place to present a "Retry" button when installing the addon via catalog fails. I'm curious why it's not failing / presenting that button.

Does the addon eventually succeed, it just takes a VERY long time to download? Or is it failing and never switching off the "Loading" text? Can you recreate and submit us your log file (you can access the `ajour.log` file from the data directory.. `Settings -> Open Data Directory`?

**Comment by kiddingbaby** [comment]
Never switching off "Loading" text , and display: "Failed to download catalog" in the title, but sometimes OK when I switch networks, and here is the ERROR logs.

09:59:08.584 [ajour_core::parse][DEBUG] Retail - parsing addons folder
09:59:08.584 [ajour_core::parse][DEBUG] Classic - parsing addons folder
09:59:08.584 [ajour_core::parse][DEBUG] Retail PTR - parsing addons folder
09:59:08.584 [ajour_core::parse][DEBUG] Retail Beta - parsing addons folder
09:59:08.584 [ajour_core::parse][DEBUG] Classic PTR - parsing addons folder
09:59:08.587 [ajour_core::parse][DEBUG] Retail - 301 folders in AddOns directory to parse
09:59:08.593 [ajour::gui::update][DEBUG] Message::CheckWeakAurasInstalled(Retail, is_installed: true)
09:59:08.593 [ajour::gui::update][DEBUG] Message::CheckWeakAurasInstalled(Retail PTR, is_installed: false)
09:59:08.593 [ajour::gui::update][DEBUG] Message::CheckWeakAurasInstalled(Retail Beta, is_installed: false)
09:59:08.593 [ajour::gui::update][DEBUG] Message::CheckWeakAurasInstalled(Classic PTR, is_installed: false)
09:59:08.593 [ajour::gui::update][DEBUG] Message::CheckWeakAurasInstalled(Classic, is_installed: false)
09:59:08.593 [ajour::gui::update][DEBUG] Message::LatestBackup(None)
09:59:08.601 [ajour::gui::update][DEBUG] Message::ListWeakAurasAccounts(Retail, num_accounts: 9)
09:59:08.643 [ajour][ERROR] Failed to parse addons
09:59:08.643 [ajour][ERROR] caused by: Addon directory not found: "C:\\Program Files (x86)\\World of Warcraft\\_classic_\\Interface/AddOns"
09:59:08.662 [ajour][ERROR] Failed to parse addons
09:59:08.662 [ajour][ERROR] caused by: Addon directory not found: "C:\\Program Files (x86)\\World of Warcraft\\_ptr_\\Interface/AddOns"
09:59:08.677 [ajour][ERROR] Failed to parse addons
09:59:08.677 [ajour][ERROR] caused by: Addon directory not found: "C:\\Program Files (x86)\\World of Warcraft\\_beta_\\Interface/AddOns"
09:59:08.691 [ajour_core::parse][DEBUG] Retail - 301 fingerprints: 301 cached, 0 calculated, 0 added, 0 removed
09:59:08.694 [ajour][ERROR] Failed to parse addons
09:59:08.694 [ajour][ERROR] caused by: Addon directory not found: "C:\\Program Files (x86)\\World of Warcraft\\_classic_ptr_\\Interface/AddOns"
09:59:08.834 [ajour_core::parse][DEBUG] Retail - 300 addon folders successfully parsed from '.toc'
09:59:08.835 [ajour_core::parse][DEBUG] Retail - 0 valid cache entries retrieved
09:59:08.835 [ajour_core::parse][DEBUG] Retail - 300 unique fingerprints to check against curse api
09:59:09.630 [ajour][ERROR] Failed to download catalog
09:59:09.630 [ajour][ERROR] caused by: CouldntResolveHost: couldn't resolve host name
09:59:09.796 [ajour::gui::update][DEBUG] Interaction::ModeSelected(Catalog)
09:59:10.222 [ajour::gui::update][DEBUG] Message::LatestRelease(None)
09:59:11.532 [ajour::gui::update][DEBUG] Message::ParsedAuras(Retail, num_auras: 1)
09:59:13.258 [ajour_core::parse][DEBUG] Retail - 55 curse packages fetched
09:59:13.258 [ajour_core::parse][DEBUG] Retail - 0 tukui packages fetched
09:59:43.267 [ajour][ERROR] Failed to parse addons
09:59:43.267 [ajour][ERROR] caused by: Timeout: request took longer than the configured timeout
10:01:20.238 [ajour::gui::update][DEBUG] Interaction::ModeSelected(Settings)
10:01:24.800 [ajour::gui::update][DEBUG] Interaction::OpenDirectory("C:\\Users\\THINKPAD\\AppData\\Roaming\\ajour")

![image](https://user-images.githubusercontent.com/15642594/109585179-f47d3580-7b3d-11eb-8049-07217b1a403b.png)

**Comment by casperstorm** [comment]
Ajour is fetching the catalog from here: https://raw.githubusercontent.com/ajour/ajour-catalog/master/catalog-2.0.json
Are you able to view it? I assume that never loads which is then connection to Github.

I really don't know what the best solution here is. Offer to host the catalog somewere else? Ideas @tarkah?

**Comment by kiddingbaby** [comment]
I did a test for ajour.exe by "proxifier". 

First, I‘m not add ajour.exe to the proxy rule, to start the ajour.exe, after a time,  ERROR msg "Failed to download catalog" display 
in the title, and "Loading" text never switching off.

Then, I add ajour.exe to proxy rule, but i can't change "Loading" text until i restart ajour.exe, This is why I want a "redownload" button, just like "refresh" button in "My Addons" page.

**Comment by casperstorm** [comment]
Released in [1.2.3-rc.1](https://github.com/ajour/ajour/releases/tag/1.2.3-rc.1).
Make sure to set Ajour Update Channel to Beta in order download this pre-release.
