### ISSUE TITLE
Part of the text is not displayed

### ISSUE THREAD

**Issue by qyh214** [ajour/ajour#556]
**Describe the bug**
If wa title or addons name is not English word,for example wa is chinese. will show blank.

**To Reproduce**
1. install an Non English characters WA.
2. see my wa

**Expected behavior**
support Non English characters.

**Screenshots**
![QQ截图20210302153507](https://user-images.githubusercontent.com/3896160/109613965-e09cf800-7b6c-11eb-9e52-7d6b6acaca13.png)

https://wago.io/prideful

**Software involved**
Please complete the following information:
 - OS: Windows 10
 - Ajour version: 0.7.2
 - (if applicable) Addon name, flavor (classic or retail) and version:NA

**Additional context**

**Log Output**
Paste the content of `ajour.log` from `%APPDATA%\ajour\ajour.log` on Windows or `$HOME/.config/ajour/ajour.log` on Mac/Linux.

**Comment by casperstorm** [comment]
Hmm, I am afraid we cant do anything about this right since our GUI framework [does not support complex characters](https://github.com/hecrj/iced/issues/213).

So until further we are locked by upstream.

**Comment by casperstorm** [comment]
I'll be closing this since we are keeping an eye on it from this PR: https://github.com/ajour/ajour/pull/518.
