### ISSUE TITLE
Addons not showing new updates.

### ISSUE THREAD

**Issue by Drake356** [ajour/ajour#559]
With the release of 9.0.5 breaking almost every addon I was eager to update all of them, but Ajour only had a handful showing updates but checking on curseforge shows that there are updates for some that are not showing on Ajour such as DBM Showing an out of date version when a new one has been on curseforge for over 5 hours now.
https://puu.sh/HnI9b.png
https://puu.sh/HnIa5.png

edit: It seems Wowup is doing the same thing, so I'm not sure if this is some kind of issue with Curse?

**Comment by tarkah** [comment]
Curse's API is just super slow to update with new releases. I actually experienced this firsthand yesterday as I'm rolling out a new feature here #562 to check for addon updates automatically.

The few addons I installed that JUST had new releases on Curse, took over 5 hours for their API to update. That'll affect all addon managers unfortunately :/

**Comment by tarkah** [comment]
@Drake356 I'm going to go ahead and close this

**Comment by Drake356** [comment]
Alright, I was figuring it had something to do with curse's api since it wasn't just Ajour, just left the issue open just to be sure, thanks for responding though.
