### ISSUE TITLE
No fonts displayed.

### ISSUE THREAD

**Issue by fhhelling** [ajour/ajour#565]
**Describe the bug**
No fonts can be seen, whether with or without antialiasing.

**To Reproduce**
1. Start ajour

**Expected behavior**
Fonts should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/49715820/111010435-d3ff7780-8396-11eb-9830-af32df0482b3.png)

**Software involved**
Please complete the following information:
 - OS: Microsoft Windows 10 20H2 (Build 19042.844)
 - Ajour version: 0.7.2

**Log Output**

> 00:54:04.002 [ajour][INFO] Ajour 0.7.2 has started.
> 00:54:04.008 [ajour::gui][DEBUG] config loaded:
> Config {
>     wow: Wow {
>         directory: None,
>         flavor: Retail,
>     },
>     addons: Addons {
>         global_release_channel: Stable,
>         ignored: {},
>         release_channels: {},
>         delete_saved_variables: false,
>     },
>     theme: None,
>     column_config: V1 {
>         local_version_width: 150,
>         remote_version_width: 150,
>         status_width: 85,
>     },
>     window_size: None,
>     scale: None,
>     backup_directory: None,
>     backup_addons: false,
>     backup_wtf: false,
>     hide_ignored_addons: false,
>     self_update_channel: Stable,
>     weak_auras_account: {},
>     alternating_row_colors: false,
>     language: English,
>     catalog_source: None,
> }
> 00:54:04.008 [ajour::gui][DEBUG] antialiasing: true
> 00:54:04.240 [ajour_core::utility][DEBUG] checking for application update
> 00:54:04.240 [ajour_core::theme][DEBUG] loading user themes
> 00:54:04.242 [ajour_core::fs::theme][DEBUG] loaded 0 user themes
> 00:54:04.278 [ajour::gui::update][DEBUG] Message::ThemesLoaded(0 themes)
> 00:54:04.278 [ajour::gui::update][DEBUG] Message::CachesLoaded(error: false)
> 00:54:04.286 [ajour::gui::update][DEBUG] Message::Parse
> 00:54:04.286 [ajour::gui::update][DEBUG] addon directory is not set, showing welcome screen
> 00:54:04.371 [ajour::gui::update][DEBUG] Message::LatestRelease(Some("0.7.2"))
> 00:54:04.786 [ajour_core::catalog][DEBUG] Etag match, cached catalog is latest version
> 00:54:04.842 [ajour::gui::update][DEBUG] Message::CatalogDownloaded(15994 addons in catalog)

**Comment by casperstorm** [comment]
@fhhelling Try the OpenGL version of Ajour. That should fix the issue: https://github.com/ajour/ajour/releases/tag/0.7.2
