### ISSUE TITLE
Empty ajour folder in %APPDATA% with --data argument

### ISSUE THREAD

**Issue by jppaled** [ajour/ajour#576]
**Describe the bug**
Even if I pass `--data` argument with the custom path, an **empty** "ajour" folder is created in %APPDATA%

**To Reproduce**
1. create a shortcut of ajour.exe
2. add `--data` argument with a custom path
3. save
4. execute the shortcut
5. go to %APPDATA% and you will see an empty "ajour" folder

**Expected behavior**
I expected to not see an ajour folder in  %APPDATA% because i specify the data directory

**Screenshots**

**Software involved**
Please complete the following information:
 - OS: "Windows 10"
 - Ajour version: "0.7.2"

**Additional context**

**Log Output**
Paste the content of `ajour.log` from `%APPDATA%\ajour\ajour.log` on Windows or `$HOME/.config/ajour/ajour.log` on Mac/Linux.

**Comment by casperstorm** [comment]
I can reproduce this on MacOS as well. I'll take a look. Thanks for reporting this.

**Comment by casperstorm** [comment]
I've merged a fix to development. It will be coming out with the next release.
