### ISSUE TITLE
Config synchronization between PCs

### ISSUE THREAD

**Issue by scoiatael** [ajour/ajour#577]
I'm playing WoW on multiple PC (macOS laptop, Windows PC, occasionally Linux PC).

Really nice feature of Curse client was ability to synchronize list of addons. I started to think that maybe we could go step further here and synchronize also settings? After all, there's already code to backup both config and addon folders :)

This, of course, requires a backend with some sort of user identity management. I believe I'll have some credits from https://fly.io/ available on hand and I'd be willing to implement this feature (both API -- Elixir and client code -- Rust, here).

Would you be open to this idea? If so, let's use this issue to design requirements :)

**Comment by tarkah** [comment]
We've had this suggested in the past, and we believe there are other tools better suited for this task.

I'd HIGHLY recommend checking out https://syncthing.net/. It's the ultimate tool for syncing folders between devices seamlessly and fairly easily.

**Comment by casperstorm** [comment]
I think its an awesome idea, @scoiatael and it has been brought up a few times before (https://github.com/ajour/ajour/issues/509, https://github.com/ajour/ajour/discussions/172). However, I agree with @tarkah and think theres better tools for it, syncthing is a good example as he also suggests.
One of the major benefits with Ajour is the simplicity and we try very hard to keep it that way and in that process unfortunately have to cut away some feature.
