### ISSUE TITLE
Wago Menu crashes

### ISSUE THREAD

**Issue by gageracer** [ajour/ajour#587]
**Describe the bug**
When I try to open the Wago menu, the app crashes.
`16:08:18.513 [panic][ERROR] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: KeyError("Invalid key: sayı")': src/gui/element`

SAYI is the Turkish word for number, I didn't have this issue with .7 version also using it in Turkish. 

**Software involved**
Please complete the following information:
 - OS: Manjaro 5.10 Linux
 - Ajour version: 1

**Additional context**

**Log Output**
16:08:15.998 [ajour][INFO] Ajour 1.0.0 has started.
16:08:16.014 [ajour::gui][DEBUG] config loaded:
Config {
    wow: Wow {
        directory: None,
        directories: {
            RetailPTR: "/home/can/Games/world-of-warcraft/drive_c/Program Files (x86)/World of Warcraft/_ptr_",
            Retail: "/home/can/Games/world-of-warcraft/drive_c/Program Files (x86)/World of Warcraft/_retail_",
        },
        flavor: Retail,
    },
    addons: Addons {
        global_release_channel: Stable,
        ignored: {
            Retail: [],
            RetailPTR: [],
        },
        release_channels: {
            RetailPTR: {},
            Retail: {
                "Grid2": Stable,
            },
        },
        delete_saved_variables: false,
    },
    theme: Some(
        "Dark",
    ),
    column_config: V3 {
        my_addons_columns: [
            ColumnConfigV2 {
                key: "title",
                width: None,
                hidden: false,
            },
            ColumnConfigV2 {
                key: "local",
                width: Some(
                    150,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "remote",
                width: Some(
                    150,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "status",
                width: Some(
                    85,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "channel",
                width: Some(
                    85,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "author",
                width: Some(
                    85,
                ),
                hidden: true,
            },
            ColumnConfigV2 {
                key: "game_version",
                width: Some(
                    110,
                ),
                hidden: false,
            },
        ],
        catalog_columns: [
            ColumnConfigV2 {
                key: "addon",
                width: Some(
                    150,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "description",
                width: None,
                hidden: false,
            },
            ColumnConfigV2 {
                key: "source",
                width: Some(
                    85,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "num_downloads",
                width: Some(
                    105,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "install_retail",
                width: Some(
                    85,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "install_classic",
                width: Some(
                    85,
                ),
                hidden: false,
            },
        ],
        aura_columns: [],
    },
    window_size: Some(
        (
            1896,
            1008,
        ),
    ),
    scale: Some(
        1.0,
    ),
    backup_directory: Some(
        "/home/can/wowbackup",
    ),
    backup_addons: false,
    backup_wtf: true,
    hide_ignored_addons: false,
    self_update_channel: Stable,
    weak_auras_account: {
        Retail: "GAGERACER",
    },
    alternating_row_colors: true,
    language: Turkish,
    catalog_source: Some(
        Curse,
    ),
    auto_update: false,
}
16:08:16.014 [ajour::gui][DEBUG] antialiasing: true
16:08:16.198 [ajour_core::utility][DEBUG] checking for application update
16:08:16.200 [ajour_core::theme][DEBUG] loading user themes
16:08:16.205 [ajour_core::fs::theme][DEBUG] loaded 0 user themes
16:08:16.395 [ajour::gui::update][DEBUG] Message::ThemesLoaded(0 themes)
16:08:16.395 [ajour::gui::update][DEBUG] Message::CachesLoaded(error: false)
16:08:16.408 [ajour::gui::update][DEBUG] Message::Parse
16:08:16.408 [ajour::gui::update][DEBUG] preparing to parse addons in "/home/can/Games/world-of-warcraft/drive_c/Program Files (x86)/World of Warcraft/_ptr_/Interface/AddOns"
16:08:16.408 [ajour::gui::update][DEBUG] preparing to parse addons in "/home/can/Games/world-of-warcraft/drive_c/Program Files (x86)/World of Warcraft/_retail_/Interface/AddOns"
16:08:16.408 [ajour_core::parse][DEBUG] Retail PTR - parsing addons folder
16:08:16.408 [ajour_core::parse][DEBUG] Retail - parsing addons folder
16:08:16.408 [ajour_core::parse][DEBUG] Retail PTR - 29 folders in AddOns directory to parse
16:08:16.409 [ajour_core::parse][DEBUG] Retail - 155 folders in AddOns directory to parse
16:08:16.409 [ajour_core::parse][DEBUG] Retail PTR - 29 fingerprints: 29 cached, 0 calculated, 0 added, 0 removed
16:08:16.414 [ajour_core::parse][DEBUG] Retail - 155 fingerprints: 155 cached, 0 calculated, 0 added, 0 removed
16:08:16.414 [ajour_core::parse][DEBUG] Retail PTR - 27 addon folders successfully parsed from '.toc'
16:08:16.414 [ajour_core::parse][DEBUG] Retail PTR - 0 valid cache entries retrieved
16:08:16.414 [ajour_core::parse][DEBUG] Retail PTR - 27 unique fingerprints to check against curse api
16:08:16.417 [ajour_core::parse][DEBUG] Retail - 154 addon folders successfully parsed from '.toc'
16:08:16.417 [ajour_core::parse][DEBUG] Retail - 1 valid cache entries retrieved
16:08:16.417 [ajour_core::parse][DEBUG] Retail - 152 unique fingerprints to check against curse api
16:08:16.531 [ajour::gui::update][DEBUG] Message::LatestBackup(Some(2021-03-23T16:06:21))
16:08:16.531 [ajour::gui::update][DEBUG] Message::CheckWeakAurasInstalled(Retail PTR, is_installed: true)
16:08:16.531 [ajour::gui::update][DEBUG] Message::CheckWeakAurasInstalled(Retail, is_installed: true)
16:08:16.600 [ajour::gui::update][DEBUG] Message::ListWeakAurasAccounts(Retail PTR, num_accounts: 0)
16:08:16.600 [ajour::gui::update][DEBUG] Message::ListWeakAurasAccounts(Retail, num_accounts: 2)
16:08:16.768 [ajour::gui::update][DEBUG] Message::LatestRelease(Some("1.0.0"))
16:08:16.950 [ajour_core::catalog][DEBUG] Etag match, cached catalog is latest version
16:08:17.031 [ajour::gui::update][DEBUG] Message::CatalogDownloaded(16022 addons in catalog)
16:08:17.152 [ajour_core::parse][DEBUG] Retail PTR - 6 curse packages fetched
16:08:17.152 [ajour_core::parse][DEBUG] Retail PTR - 0 tukui packages fetched
16:08:17.291 [ajour::gui::update][DEBUG] Message::ParsedAuras(Retail, num_auras: 20)
16:08:17.460 [ajour_core::parse][DEBUG] Retail PTR - 1 wowi packages fetched
16:08:17.460 [ajour_core::parse][DEBUG] Retail PTR - 0 townlong packages fetched
16:08:17.460 [ajour_core::parse][DEBUG] Retail PTR - 0 git packages fetched
16:08:17.461 [ajour_core::parse][DEBUG] Retail PTR - 5 addons built from curse packages
16:08:17.461 [ajour_core::parse][DEBUG] Retail PTR - 0 addons built from tukui packages
16:08:17.461 [ajour_core::parse][DEBUG] Retail PTR - 0 addons built from wowi packages
16:08:17.461 [ajour_core::parse][DEBUG] Retail PTR - 0 addons built from townlong-yak packages
16:08:17.461 [ajour_core::parse][DEBUG] Retail PTR - 0 addons built from git packages
16:08:17.461 [ajour_core::parse][DEBUG] Retail PTR - 1 unknown addon folders
16:08:17.461 [ajour_core::parse][DEBUG] Retail PTR - 6 addons successfully parsed
16:08:17.464 [ajour::gui::update][DEBUG] Message::ParsedAddons(Retail PTR, 6 addons)
16:08:17.740 [ajour_core::parse][DEBUG] Retail - 91 curse packages fetched
16:08:17.858 [ajour_core::parse][DEBUG] Retail - 1 tukui packages fetched
16:08:18.005 [ajour_core::parse][DEBUG] Retail - 20 wowi packages fetched
16:08:18.005 [ajour_core::parse][DEBUG] Retail - 0 townlong packages fetched
16:08:18.005 [ajour_core::parse][DEBUG] Retail - 0 git packages fetched
16:08:18.007 [ajour_core::parse][DEBUG] Retail - 82 addons built from curse packages
16:08:18.007 [ajour_core::parse][DEBUG] Retail - 1 addons built from tukui packages
16:08:18.007 [ajour_core::parse][DEBUG] Retail - 0 addons built from wowi packages
16:08:18.007 [ajour_core::parse][DEBUG] Retail - 0 addons built from townlong-yak packages
16:08:18.007 [ajour_core::parse][DEBUG] Retail - 0 addons built from git packages
16:08:18.007 [ajour_core::parse][DEBUG] Retail - 2 unknown addon folders
16:08:18.007 [ajour_core::parse][DEBUG] Retail - 85 addons successfully parsed
16:08:18.013 [ajour::gui::update][DEBUG] Message::ParsedAddons(Retail, 85 addons)
16:08:18.492 [ajour::gui::update][DEBUG] Interaction::ModeSelected(MyWeakAuras(Retail))
16:08:18.513 [panic][ERROR] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: KeyError("Invalid key: sayı")': src/gui/element/my_weakauras.rs:84
   0: <unknown>
   1: std::panicking::rust_panic_with_hook
   2: <unknown>
   3: <unknown>
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: std::rt::lang_start_internal
  20: <unknown>
  21: __libc_start_main
  22: <unknown>

**Comment by casperstorm** [comment]
I've solved the mystery. The culprit was this key:

https://github.com/ajour/ajour/blob/6b207c0b28b6932928f59f8f49a829a8959d2594/locale/tr.json#L89

This is supposed to be `number`. I am releasing a new version soon.
