### ISSUE TITLE
"Exclude" flag reset on addons in v1.0.0

### ISSUE THREAD

**Issue by FlyingHigh83** [ajour/ajour#596]
**Describe the bug**
In v1.0.0, addons I had set to be excluded had lost this setting. When I exclude them again, the flag resets, possibly when the new version does it's auto-check for updates.

**To Reproduce**
1. Run v1.0.0
2. Click on "Exclude" for an addon that has an update available, Status turns from "Update" to "Excluded"
3. Leave application running for several minutes.
4. "Exclude" has reset, Status has changed to "Update" again.

**Expected behavior**
Excluded addons remain excluded even when updates are available.

**Screenshots**
N/A

**Software involved**
Observed since Ajour v1.0.0, worked as expected in previous versions.

**Comment by casperstorm** [comment]
Good catch, @FlyingHigh83.
I have reproduced this and will make a fix. Technically it is still excluded so hitting "Update all" will actually not update it, just so you know until i have a fix out.

**Comment by FlyingHigh83** [comment]
Thanks for the giga fast response and the additional insights, looking forward to the fix. Keep up the good work!

**Comment by casperstorm** [comment]
I have fixed the issue @FlyingHigh83 - I'll push a `1.0.1-rc.2` release today or tomorrow.

**Comment by casperstorm** [comment]
@FlyingHigh83: https://github.com/ajour/ajour/releases/tag/1.0.1-rc.2
