### ISSUE TITLE
Sometimes Ajour can't find any installed addons

### ISSUE THREAD

**Issue by RENgOLD** [ajour/ajour#602]
**Describe the bug**
Sometimes (i cant find pattern, it really random) Ajour can't find any installed addons (classic and retail).
Log file in attachments.
[ajour.log](https://github.com/ajour/ajour/files/6224849/ajour.log)

**Comment by casperstorm** [comment]
Seems to be your connection failing:

```
02:06:03.148 [ajour][ERROR] caused by: failed to connect to the server
02:06:03.148 [ajour][ERROR] caused by: [35] SSL connect error

```

Do you have any network ad-blockers? And what DNS are you using? The problem is on your end to the curse server.

**Comment by RENgOLD** [comment]
google DNS (8.8.8.8/1.1.1.1) and only browser-side ad-blockers (plugins)

**Comment by casperstorm** [comment]
All right. I can't really debug it any further since it's between your network and Curse, however you can try to cURL the command and see if you can find any patterns:

```sh
curl --header "Content-Type: application/json" \
  --request POST \
  --data '[69254]' \
  https://addons-ecs.forgesvc.net/api/v2/addon/
```
