### ISSUE TITLE
Synchronize add-ons from Git repo

### ISSUE THREAD

**Issue by LenweSaralonde** [ajour/ajour#611]
As an add-on developer, I want to be able to safely synchronize my add-ons from the git repository in Ajour without losing any WIP.

If a `.git` folder is present in the add-on folder and the `git` command is available on the system:
* Add "Git &lt;remote branch name&gt;" to the Release channel selector (using `git branch -r`). The current git branch is selected by default.
* Check if an update is available using git commands such as `git fetch origin` and `git log HEAD..<remote branch name> --oneline`.
* Update using `git pull`
* Do not update and notify if the repository can't be safely synchronized (has uncommitted changes `git status --porcelain` or has unpushed commits `git log <remote branch name>..HEAD --oneline`) to prevent losing any WIP.

**Comment by casperstorm** [comment]
Thank you for the suggestion, @LenweSaralonde.
However, I don't believe Ajour should be managing a git repo. What I would suggest is to use symlink and then exclude the addon in Ajour. That is what I do when developing addons.

**Comment by LenweSaralonde** [comment]
So, maybe exclude by default add-ons that have a .git .svn or .hg folder ?
