### ISSUE TITLE
MacOS Big Sur compliant icon

### ISSUE THREAD

**Issue by lukzmu** [ajour/ajour#613]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
As `BigSur` is out for quite some time, it would be nice to make the `Ajour` icon compliant with the MacOS guidelines. Many other applications have done that eg. Discord, Slack, Github Desktop, 1Password etc.

The app looks strange as compared to other applications on the dock.

**Describe alternatives you've considered**
One can manually edit the icon, but that isn't the best way to do it, is it?

**Additional context**
N/A

**Comment by casperstorm** [comment]
We did actually spend time on updating the Ajour logo specifically for Big Sur. [You can see both here](https://github.com/ajour/ajour/tree/master/resources/logo/1024x1024).
The [HIG for Big Sur icons](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon) states that:

> In macOS 11, app icons share a common set of visual attributes, including the rounded-rectangle shape, front-facing perspective, level position, and uniform drop shadow.

> To give context to your app’s purpose, you can use the icon background to portray the tool’s environment or the items it affects. [...] it often works well to let it float just above the background and extend slightly past the icon boundaries.


If we take a closer look at the below image we see all four apps having the rounded-rectangle shape but only Ajour and Xcode utilizing the idea of extending beyond the icon boundaries. This is allowed and still within the HIG for icons on Big Sur.

<img width="334" alt="Screenshot 2021-04-06 at 15 19 29" src="https://user-images.githubusercontent.com/2248455/113717148-9d91ef80-96eb-11eb-99ba-a32c8d63c582.png">

**Comment by lukzmu** [comment]
I can see the commit was on November 2020, although when I open Ajour on macOS, this is how the icon appears.

<img width="86" alt="Screenshot 2021-04-06 at 15 34 57" src="https://user-images.githubusercontent.com/80778518/113719303-c31ff880-96ed-11eb-9b62-c3ac8f8d333b.png">

**Comment by casperstorm** [comment]
> I can see the commit was on November 2020, although when I open Ajour on macOS, this is how the icon appears.
> 
> It seems to take the default `ajour.png` icon instead of `ajour_macos.png` for macOS.

In order to update from the old icon to the new you need to re-download the .app again. We only update the binary when you update though the in-app updater. You can [download it from here](https://github.com/ajour/ajour/releases/tag/1.0.1).

The icon bundled within the .app file, which you can see [here](https://github.com/ajour/ajour/tree/master/resources/osx/Ajour.app/Contents/Resources). It does not use any .png file but a .icns file.

**Comment by lukzmu** [comment]
Re-downloading the application solved the issue. Thanks!

**Comment by casperstorm** [comment]
> Re-downloading the application solved the issue. Thanks!

Enjoy, hope you the icon fits better onto your bar :)
