### ISSUE TITLE
very minor visual annoyance (not even a bug]

### ISSUE THREAD

**Issue by Altoholic** [ajour/ajour#623]
**Describe the bug**
The local versions and the latest versions differ visually, but they are in fact the same.

**Expected behavior**
Versions numbers should be complete, to avoid confusion.

**Screenshots**
https://imgur.com/a/0jw5BLx

**Software involved**
Please complete the following information:
 - OS: "Windows 10"
 - Ajour version: 1.1.0
 - classic WoW

**Comment by casperstorm** [comment]
Hmm this looks strange, do all addons have a source? They should be the same, actually. Take a look at my screenshot below:

<img width="406" alt="local-latest" src="https://user-images.githubusercontent.com/2248455/114984269-d8d1b280-9e91-11eb-988d-aae471037c81.PNG">

**Comment by Altoholic** [comment]
Oh, it's not addons, it's WA. My bad, i forget to precise that point.

**Comment by casperstorm** [comment]
I see, this is unfortunately not something we can do anything about. It is related to the data we are getting from the API. :-(
However, I see the "problem" and now I can't unsee it as well. Haha.
