### ISSUE TITLE
Multible instance of Ajour in systemtray

### ISSUE THREAD

**Issue by mrkhaglund** [ajour/ajour#624]
If you choose to let Ajour start to system tray automatically when windows starts and then start ajour manually, you get several Ajour instances in the systemtray

Ajour 1.1.0
Windows 10 20H2, OS Version: 19042.928

**Comment by casperstorm** [comment]
We allowed multiple instances initially to support using Ajour with multiple WoW directories, however that is support now and with the introduction of System Tray support I agree that this is indeed a little confusing.

@tarkah did you research this subject?

**Comment by tarkah** [comment]
@casperstorm I've got some ideas. I'll try to tackle this week.

**Comment by tarkah** [comment]
This has been fixed and will be in the next release.
