### ISSUE TITLE
Need documentation for addon authors

### ISSUE THREAD

**Issue by SpareSimian** [ajour/ajour#626]
What must I do to prepare [my addon](https://github.com/SpareSimian/ListDailies) for Ajour? I've got one on GitHub. What steps do I follow to make it Ajour-friendly?

**Comment by AcidWeb** [comment]
Most sane approach is using https://github.com/BigWigsMods/packager + GitHub Actions. That way you can automate creating 
 the release package and upload it to multiple sources simultaneously.

Output of that packager uploaded as GitHub release is enough to be supported by Ajour and other third party addon updaters.

**Comment by mlablah** [comment]
@SpareSimian: AcidWeb has already provided a succinct recommendation, but in case you want the nitty gritty of what needs to be done and why, here's a more verbose explanation.

If a user adds an addon to Ajour via the "Install from URL" action, Ajour will look for the `release` marked as `latest release` on that repo. 
If that release has a zip file asset, Ajour will download and extract it to the addons folder of the wow flavor currently selected by the user.
If the user switches the `Release channel` of the addon (inside Ajour) to Alpha or Beta, Ajour will also look at releases that are marked as "pre-release". The Alpha/Beta labels stem from CurseForge, but we decided to also use them for our GitHub/GitLab integration.
When looking for updates, Ajour will compare the tag of whatever is currently the latest release, to the tag that was cached last time the addon was installed/updated. If they don't match, Ajour will update the addon.

For inspiration on how to do this, you can have a look at one of @casperstorm 's addon repos: 
https://github.com/casperstorm/overshields/releases/latest

And here is the github action workflow he uses to create the releases: https://github.com/casperstorm/overshields/blob/main/.github/workflows/release_to_draft.yml

**Comment by SpareSimian** [comment]
Thanks! I gathered both comments and added them to the wiki.
