### ISSUE TITLE
"Theme alreacy exists with that name"

### ISSUE THREAD

**Issue by tordenflesk** [ajour/ajour#637]
**Describe the bug**
Unable to import theme, "theme already exists with that name"

**To Reproduce**
1. https://theme.getajour.com/?theme=%7B%22name%22:%22KTZ%22,%22palette%22:%7B%22base%22:%7B%22background%22:%22#d6d7d2%22,%22foreground%22:%22#d6d7d2%22%7D,%22normal%22:%7B%22primary%22:%22#808080%22,%22secondary%22:%22#434343%22,%22surface%22:%22#434343%22,%22error%22:%22#434343%22%7D,%22bright%22:%7B%22primary%22:%22#434343%22,%22secondary%22:%22#f5f5f5%22,%22surface%22:%22#973838%22,%22error%22:%22#C13047%22%7D%7D%7D
2. Paste in Ajour
3. receive "theme already exists with that name" error

**Expected behavior**
clean import

**Screenshots**
https://i.imgur.com/uXuafKv.png

**Software involved**

 - Ajour version: 1.1.0

**Log Output**
23:39:38.651 [ajour::gui::update][DEBUG] Interaction::ImportTheme(https://theme.getajour.com?theme=%7B%22name%22%3A%22KTZ%22%2C%22palette%22%3A%7B%22base%22%3A%7B%22background%22%3A%22%23d6d7d2%22%2C%22foreground%22%3A%22%23d6d7d2%22%7D%2C%22normal%22%3A%7B%22primary%22%3A%22%23808080%22%2C%22secondary%22%3A%22%23434343%22%2C%22surface%22%3A%22%23434343%22%2C%22error%22%3A%22%23434343%22%7D%2C%22bright%22%3A%7B%22primary%22%3A%22%23434343%22%2C%22secondary%22%3A%22%23f5f5f5%22%2C%22surface%22%3A%22%23973838%22%2C%22error%22%3A%22%23C13047%22%7D%7D%7D)
23:39:38.656 [ajour_core::fs::theme][DEBUG] loaded 1 user themes
23:39:38.656 [ajour][ERROR] Theme already exists with that name
23:39:38.656 [ajour][ERROR] caused by: Failed to Import Theme
23:39:38.656 [ajour][ERROR] caused by: Theme already exists with name: KTZ
23:39:55.725 [ajour::gui::update][DEBUG] Interaction::ImportTheme(https://theme.getajour.com?theme=%7B%22name%22%3A%22KTZ%22%2C%22palette%22%3A%7B%22base%22%3A%7B%22background%22%3A%22%23d6d7d2%22%2C%22foreground%22%3A%22%23d6d7d2%22%7D%2C%22normal%22%3A%7B%22primary%22%3A%22%23808080%22%2C%22secondary%22%3A%22%23434343%22%2C%22surface%22%3A%22%23434343%22%2C%22error%22%3A%22%23434343%22%7D%2C%22bright%22%3A%7B%22primary%22%3A%22%23434343%22%2C%22secondary%22%3A%22%23f5f5f5%22%2C%22surface%22%3A%22%23973838%22%2C%22error%22%3A%22%23C13047%22%7D%7D%7D)
23:39:55.731 [ajour_core::fs::theme][DEBUG] loaded 1 user themes
23:39:55.731 [ajour][ERROR] Theme already exists with that name
23:39:55.731 [ajour][ERROR] caused by: Failed to Import Theme
23:39:55.731 [ajour][ERROR] caused by: Theme already exists with name: KTZ
23:40:01.188 [ajour::gui::update][DEBUG] Message::ThemeSelected("Sort")
23:40:25.649 [ajour::gui::update][DEBUG] Interaction::ImportTheme(https://theme.getajour.com?theme=%7B%22name%22%3A%22KTZ%22%2C%22palette%22%3A%7B%22base%22%3A%7B%22background%22%3A%22%23d6d7d2%22%2C%22foreground%22%3A%22%23d6d7d2%22%7D%2C%22normal%22%3A%7B%22primary%22%3A%22%23808080%22%2C%22secondary%22%3A%22%23434343%22%2C%22surface%22%3A%22%23434343%22%2C%22error%22%3A%22%23434343%22%7D%2C%22bright%22%3A%7B%22primary%22%3A%22%23434343%22%2C%22secondary%22%3A%22%23f5f5f5%22%2C%22surface%22%3A%22%23973838%22%2C%22error%22%3A%22%23C13047%22%7D%7D%7D)
23:40:25.656 [ajour_core::fs::theme][DEBUG] loaded 1 user themes
23:40:25.656 [ajour][ERROR] Theme already exists with that name
23:40:25.656 [ajour][ERROR] caused by: Failed to Import Theme
23:40:25.656 [ajour][ERROR] caused by: Theme already exists with name: KTZ

**Comment by tarkah** [comment]
Make sure to change the "name" before clicking copy and trying to import to Ajour. You have a theme imported which already has that name.

![image](https://user-images.githubusercontent.com/10239377/117511936-7aa16800-af43-11eb-9ebf-d221032aaaa5.png)

If you need to delete a theme you imported, you can open the Data Directory from within settings. There is a theme folder you can open and delete the `.yml` file with the associate name.
