### ISSUE TITLE
[minor annoyance] [catalog] updates with no actual update

### ISSUE THREAD

**Issue by waytoomuchgaming** [ajour/ajour#638]
**Describe the bug**
Sometimes, in the catalog, you see an addon have been updated, but when you check it, it's only the shadowlands/TBC/whatever version who have been updated, not the Classic one.

**Expected behavior**
Updates filtered so i can make visible only the ones i care for (eg: Classic).

**Software involved**
OS: Windows 10
Ajour version: 1.1.0

**Comment by casperstorm** [comment]
Hmm, I am not quite sure I understand what the problem is here, @waytoomuchgaming.
The catalog will respect your selected `flavor` and only display addons for it.

Can you maybe elaborate on the issue?

**Comment by waytoomuchgaming** [comment]
eg:
Let's take one of the latest addons updated on Curse - says the catalog tab of Ajour - Elephant, 1h ago.
![Untitled](https://user-images.githubusercontent.com/336778/120983728-460b1100-c77a-11eb-949e-080d6c285528.png)

If i go on the Curse web site, i realize the TBC version of the addon have been updated 1h ago, not the Classic ERA, who have been last updated in 2020.
![Untitled2](https://user-images.githubusercontent.com/336778/120983734-46a3a780-c77a-11eb-8f38-8c838d99000f.png)

**Comment by casperstorm** [comment]
Gotcha! Okay, that make sense.
It's currently a limitation on how we do the Catalog, but we are working on a v2 which could solve this. I see this is an annoyance. Thanks for providing the feedback.

**Comment by casperstorm** [comment]
This is now awaiting #666.
