### ISSUE TITLE
[follow list]

### ISSUE THREAD

**Issue by waytoomuchgaming** [ajour/ajour#639]
**Is your feature request related to a problem? Please describe.**
As a heavy addon user, i tend to follow a lot of projects, but not using them. To avoid massive amounts of charging and updating time, i put them in the follow list of Curse.
But Curse is a mess, and not all addons are there.

**Describe the solution you'd like**
Another tab, optional (disabled by default), where i can put projects i want to follow, but not to install, so i can quickly found them when i need them.

**Describe alternatives you've considered**
A free new computer.

**Comment by casperstorm** [comment]
I feel like this does not fit into the minimalistic vision of Ajour.
I would suggest installing all addons (those you want to 'follow' as well), and then just using the in-game menu to disable/enable them once you use them.

Thanks for the suggestion.
