### ISSUE TITLE
Manage Addons for TBC Client

### ISSUE THREAD

**Issue by DavidBabel** [ajour/ajour#640]
**Is your feature request related to a problem? Please describe.**
Manage Addons for TBC Client

**Additional context**
I think it's intended, but will ajour be ajour for TBC Classic ?

**Comment by casperstorm** [comment]
We plan to have a release ready today: https://github.com/ajour/ajour/pull/629.

**Comment by tarkah** [comment]
This has been released! 

In order to get it you have to opt-in to beta builds from Settings:

`Settings -> Ajour Update Channel -> Beta`

Then it should show an update available for 1.2.0-rc.1

Or download from: 

https://github.com/ajour/ajour/releases/tag/1.2.0-rc.1
