### ISSUE TITLE
Separate Burning crusade Classic and Classic era addons

### ISSUE THREAD

**Issue by LuckyCire** [ajour/ajour#642]
It is not possible at the moment to download/update addons for TBC Classic version of the game. Only Retail/Classic are available, while some addons now have already released separate updates for TBC and classic era.

Ajour should have a "TBC Classic" option on his scrolling menu, next to "Classic" and "Retail".

**Comment by yaparadox** [comment]
update to beta ajour

**Comment by LuckyCire** [comment]
Thank you, I will close this issue then.
