### ISSUE TITLE
[minor Bug][Classic ERA] addon with incorrect Source

### ISSUE THREAD

**Issue by Altoholic** [ajour/ajour#645]
**Describe the bug**
"Movement Speed" addon have "unknow" source, despite having been installed via Ajour (via Curse).

**Expected behavior**
Source should be "CurseForge"

**Software involved**
 - OS: Windows 10
 - Ajour version: 1.2.0
 - Classic ERA

**Comment by casperstorm** [comment]
I can reproduce it, ill take a look. Thanks for reporting, @Altoholic.

**Comment by tarkah** [comment]
@Altoholic we've identified the underlying issue and are waiting for it to get fixed in the upstream API.

**Comment by casperstorm** [comment]
Upstream issue is fixed, @Altoholic. Please check if the issue is fixed, otherwise reopen.
I've just confirmed it works on my end.

**Comment by Altoholic** [comment]
Working as intended :)
