### ISSUE TITLE
[Missing addon][bcc] Raven not appearing

### ISSUE THREAD

**Issue by olepg** [ajour/ajour#647]
Hi

I'm unable to use Ajour to update Raven, through curse source or github:

https://www.curseforge.com/wow/addons/raven
https://github.com/Tojaso/Raven

I'm not sure what the issue is, but I suspect there is a issue with either the uploader or this software.

**Comment by tarkah** [comment]
Thanks for opening the issue! I've dug into this and there's a couple issues causing things to fail:

- For curse, the author is publishing 1 release and tagging it to all 3 flavors (retail, tbc classic and classic). Unfortunately with how their API is setup, we can only associate the release to 1 flavor, in this case retail. The author needs to publish separate releases, tagged individually for each respective flavor, in order for the addon managers to pick it up properly for each flavor.
- For Github to work, the author needs to add a release asset `.zip` file to their release. They can use a tool like this https://github.com/BigWigsMods/packager to handle it automatically.

**Comment by StewMcc** [comment]
Does curse still not expose this on their API. Trying to find any docs on their API has proven trickier than I expected. Outside overly simple useless examples. 

There seems to be more addon projects shifting to using it, and the curse packaging stuff 😢
