### ISSUE TITLE
[Classic ERA] Delete SavedVariables don't always delete

### ISSUE THREAD

**Issue by waytoomuchgaming** [ajour/ajour#648]
**Describe the bug**
Sometimes previous configuration of an addon stay, despite the option "Delete SavedVariables when deleting  addons" being checked.
I suspect the fact that .bak files are not deleted maybe have something to do with that.
It's not 100% reproducible, tho.

**Software involved**
Please complete the following information:
 - OS Windows 10
 - Ajour version: 1.2.0
 - Classic ERA 1.13.7

**Comment by casperstorm** [comment]
I'll take a look today and see if i can reproduce this. Keep me update if you discover more informations.

**Comment by casperstorm** [comment]
https://github.com/ajour/ajour/commit/caf10396bc99b048ff64de7c0027e67df2fe18da should have fixed this. Closing.
