### ISSUE TITLE
Install from URL doesn't work for multiply-nested GitLab projects

### ISSUE THREAD

**Issue by madcowfred** [ajour/ajour#651]
**Describe the bug**
Ajour turns a URL like `https://gitlab.com/thing-engineering/wowthing/wowthing-collector` into `https://gitlab.com/api/v4/projects/thing-engineering%2Fwowthing/releases`, when the project really is nested 3 levels deep (organization/subgroup/project).

**To Reproduce**
1. Click on `Install from URL`
2. Paste in `https://gitlab.com/thing-engineering/wowthing/wowthing-collector`
3. Click on `Install for Retail`

**Expected behavior**
Install to proceed correctly.

**Software involved**
Please complete the following information:
 - OS: Windows 10
 - Ajour version: 1.2.0

**Log Output**
```
23:39:21.670 [ajour::gui::update][DEBUG] Interaction::ModeSelected(Install)
23:39:26.153 [ajour::gui::update][DEBUG] Interaction::InstallAddon(Retail, Source)
23:39:26.647 [ajour][ERROR] No release at https://gitlab.com/api/v4/projects/thing-engineering%2Fwowthing/releases
```

**Comment by casperstorm** [comment]
Ah, I see we should support this nested structure. This is news to me, as I am not using gitlab.
@tarkah would you be up for looking into it?

**Comment by tarkah** [comment]
Relevant documentation on gitlab subgroups... https://docs.gitlab.com/ee/user/group/subgroups/

I'll look into this and fix

**Comment by tarkah** [comment]
Currently I take first two segments of the URL path to construct the API endpoint. But it seems safe for me to just take the ENTIRE path and URL encode it and use that.

**Comment by tarkah** [comment]
@madcowfred I've fixed Ajour in #654 to handle the API url for nested projects properly.

However, this repo still doesn't work because the author isn't attaching the .zip release properly.  See https://gitlab.com/api/v4/projects/thing-engineering%2Fwowthing%2Fwowthing-collector/releases/v9.0.5.3.

The "download" url is a link in the "description" of the release. The asset needs to be attached as a "link", so it shows up in the `assets.links` section. We then check any asset link that has a name that ends in ".zip", and use that.

**Comment by madcowfred** [comment]
@tarkah ah, interesting. Attaching a file to a release is apparently pretty painful with GitLab, will have to finally look at automating releases on tag push. I think I've linked it properly now if you want to try again?

**Comment by tarkah** [comment]
Worked like a charm!

```
11:14:44.861 [ajour::gui::update][DEBUG] Interaction::InstallAddon(Retail, Source)
11:14:45.473 [ajour::gui::update][DEBUG] Message::CatalogInstallAddonFetched(Retail, "https://gitlab.com/thing-engineering/wowthing/wowthing-collector")
11:14:45.473 [ajour_core::network][DEBUG] downloading remote version v9.0.5.3 for 776157126261677386
11:14:45.924 [ajour::gui::update][DEBUG] Message::DownloadedAddon((Retail, 776157126261677386, error: false))
11:14:45.950 [ajour::gui::update][DEBUG] Message::UnpackedAddon((776157126261677386, error: false))
11:14:45.951 [ajour_core::parse][DEBUG] Retail - updating fingerprint for WoWthing_Collector
11:14:45.960 [ajour::gui::update][DEBUG] Message::AddonCacheUpdated(wowthing-collector)
11:14:45.984 [ajour::gui::update][DEBUG] Message::UpdateFingerprint((Retail, WoWthing_Collector, error: false))
```

**Comment by tarkah** [comment]
I'll go ahead and merge the fix
