### ISSUE TITLE
Failed to unpack add-on (ElvUI)

### ISSUE THREAD

**Issue by watsontom100** [ajour/ajour#655]
**Describe the bug**
Since the release of TBC I can fresh install ElvUI (via Ajour) however whenever I try and update it I get "Failed to unpack addon). If I uninstall and re-install then it updates fine.

**To Reproduce**
1. Install ElvUI (v2.08)
2. Click on Update (to v2.09)

**Expected behavior**
Successfully updates

**Software involved**
Please complete the following information:
 - OS: macOS Big Sur (11.3.1)
 - Ajour version: 1.2.0
 - (if applicable) Addon name, flavor (classic or retail) and version: ElvUI tbc

**Additional context**
- WoW is installed on an external hard drive. 
- I have 20 classic tbc addons, they all update fine. 
- No other addons are installed from Tukui (everything else is Curse)

**Log Output**
15:56:55.683 [ajour::gui::update][DEBUG] Interaction::ModeSelected(MyAddons(ClassicTbc))
15:56:56.784 [ajour::gui::update][DEBUG] Interaction::Update(ElvUI)
15:56:56.784 [ajour_core::network][DEBUG] downloading remote version 2.09 for ElvUI
15:56:59.562 [ajour::gui::update][DEBUG] Message::DownloadedAddon((Classic TBC, ElvUI, error: false))
15:56:59.577 [ajour::gui::update][DEBUG] Message::UnpackedAddon((ElvUI, error: true))
15:56:59.577 [ajour][ERROR] Failed to unpack addon
15:56:59.577 [ajour][ERROR] caused by: No such file or directory (os error 2)

**Comment by tarkah** [comment]
Hmm, the only thing I can think of is a "network" issue when trying to download the new release ZIP. I just tried updating to 2.09 and it worked for me. 

Has this only happened once for you? Or can you recreate the issue over a longer period of time?

**Comment by watsontom100** [comment]
Yeah it's happened since tbc prepatch launch with every new version of Elv I've had to uninstall and re-install rather than update.

**Comment by tarkah** [comment]
Hmmm, okay. Do you have any issues downloading the zip directly from this link?

https://www.tukui.org/classic-tbc-addons.php?download=2

**Comment by watsontom100** [comment]
Nope, all fine. Also, in the end I have just deleted it and re-installed it via Ajour and it's working fine. Just odd that the update doesn't

**Comment by tarkah** [comment]
Yeah that is super weird. I'll create a special build for you to try out with a bunch of additional logging sprinkled in so we can narrow down the exact cause.

**Comment by tarkah** [comment]
@watsontom100 Try recreating the issue with this build and post back the full log file:

[Ajour.app.zip](https://github.com/ajour/ajour/files/6618170/Ajour.app.zip)

**Comment by watsontom100** [comment]
Done, sorry took me a while to force Ajour to think I had an old version of Elv but figured it out :) - logs below:

17:44:58.239 [ajour_core::network][DEBUG] downloading remote version 2.09 for ElvUI
17:45:00.690 [ajour::gui::update][DEBUG] Message::DownloadedAddon((Classic TBC, ElvUI, error: false))
17:45:00.690 [ajour_core::fs::addon][DEBUG] Unpacking addon:
Addon { primary_folder_id: "ElvUI", folders: [AddonFolder { id: "ElvUI", title: "ElvUI TBC", interface: Some("2.5.1"), path: "/Volumes/T7 Touch/Games/World of Warcraft/_classic_/Interface/AddOns/ElvUI", author: Some("Elv, Simpy"), notes: Some("User Interface replacement AddOn for World of Warcraft."), version: Some("2.08"), repository_identifiers: RepositoryIdentifiers { wowi: None, tukui: Some("2"), curse: None, git: None }, dependencies: [], fingerprint: Some(2493977118) }, AddonFolder { id: "ElvUI_OptionsUI", title: "ElvUI TBC OptionsUI", interface: Some("2.5.1"), path: "/Volumes/T7 Touch/Games/World of Warcraft/_classic_/Interface/AddOns/ElvUI_OptionsUI", author: Some("Elv, Simpy"), notes: Some("Options for ElvUI."), version: Some("2.08"), repository_identifiers: RepositoryIdentifiers { wowi: None, tukui: None, curse: None, git: None }, dependencies: ["ElvUI"], fingerprint: Some(3948528218) }], state: Unpacking, release_channel: Default, repository: Some(RepositoryPackage { kind: Tukui, id: 2, metadata: RepositoryMetadata { version: None, title: Some("ElvUI"), author: None, notes: None, website_url: Some("https://www.tukui.org/classic-tbc-addons.php?id=2"), game_version: Some("2.5.1"), file_id: None, changelog_url: Some("https://www.tukui.org/classic-tbc-addons.php?id=2&changelog"), remote_packages: {Stable: RemotePackage { version: "2.09", download_url: "https://www.tukui.org/classic-tbc-addons.php?download=2", file_id: None, date_time: Some(2021-06-08T02:04:30Z), modules: [] }} } }), details_btn_state: State { is_pressed: false }, update_btn_state: State { is_pressed: false }, delete_btn_state: State { is_pressed: false }, ignore_btn_state: State { is_pressed: false }, unignore_btn_state: State { is_pressed: false }, website_btn_state: State { is_pressed: false }, pick_release_channel_state: State { menu: State { scrollable: State { scroller_grabbed_at: None, scroll_box_touched_at: None, offset: 0.0 } }, is_open: false, hovered_option: None, last_selection: None }, changelog_btn_state: State { is_pressed: false }, remote_version_btn_state: State { is_pressed: false }, fuzzy_score: None }
17:45:00.690 [ajour_core::fs::addon][DEBUG] From directory: "/Volumes/T7 Touch/Games/World of Warcraft/_classic_"
17:45:00.690 [ajour_core::fs::addon][DEBUG] To directory: "/Volumes/T7 Touch/Games/World of Warcraft/_classic_/Interface/AddOns"
17:45:00.690 [ajour_core::fs::addon][DEBUG] Zip path: "/Volumes/T7 Touch/Games/World of Warcraft/_classic_/ElvUI"
17:45:00.690 [ajour_core::fs::addon][DEBUG] File opened
17:45:00.705 [ajour_core::fs::addon][DEBUG] Zip opened
17:45:00.706 [ajour::gui::update][DEBUG] Message::UnpackedAddon((ElvUI, error: true))
17:45:00.706 [ajour][ERROR] Failed to unpack addon
17:45:00.706 [ajour][ERROR] caused by: No such file or directory (os error 2)
17:45:03.279 [ajour::gui::update][DEBUG] Interaction::ModeSelected(Settings)

**Comment by tarkah** [comment]
Ok, can you confirm the following paths exist when you have ElvUI installed?

`/Volumes/T7 Touch/Games/World of Warcraft/_classic_/Interface/AddOns/ElvUI`
`/Volumes/T7 Touch/Games/World of Warcraft/_classic_/Interface/AddOns/ElvUI_OptionsUI`

**Comment by watsontom100** [comment]
Yep! Both in that location

**Comment by tarkah** [comment]
So weird. It's failing when trying to remove those folders, so it can unpack the Zip to those locations. And the error is `No such file or directory (os error 2)` but those folders definitely exist??

Any weird permissions issues on those folders?

**Comment by watsontom100** [comment]
Don't know if useful for pattern matching but I deleted and re-installed Elv to get the other logs (I omitted the folder creation spam at the end but let me know if there could be something useful in there):

`downloading remote version 2.09 for 5251166554282412174
17:58:19.873 [ajour::gui::update][DEBUG] Message::DownloadedAddon((Classic TBC, 5251166554282412174, error: false))
17:58:19.873 [ajour_core::fs::addon][DEBUG] Unpacking addon:
Addon { primary_folder_id: "5251166554282412174", folders: [], state: Unpacking, release_channel: Default, repository: Some(RepositoryPackage { kind: Tukui, id: 2, metadata: RepositoryMetadata { version: None, title: Some("ElvUI"), author: None, notes: None, website_url: Some("https://www.tukui.org/classic-tbc-addons.php?id=2"), game_version: Some("2.5.1"), file_id: None, changelog_url: Some("https://www.tukui.org/classic-tbc-addons.php?id=2&changelog"), remote_packages: {Stable: RemotePackage { version: "2.09", download_url: "https://www.tukui.org/classic-tbc-addons.php?download=2", file_id: None, date_time: Some(2021-06-08T02:04:30Z), modules: [] }} } }), details_btn_state: State { is_pressed: false }, update_btn_state: State { is_pressed: false }, delete_btn_state: State { is_pressed: false }, ignore_btn_state: State { is_pressed: false }, unignore_btn_state: State { is_pressed: false }, website_btn_state: State { is_pressed: false }, pick_release_channel_state: State { menu: State { scrollable: State { scroller_grabbed_at: None, scroll_box_touched_at: None, offset: 0.0 } }, is_open: false, hovered_option: None, last_selection: None }, changelog_btn_state: State { is_pressed: false }, remote_version_btn_state: State { is_pressed: false }, fuzzy_score: None }
17:58:19.873 [ajour_core::fs::addon][DEBUG] From directory: "/Volumes/T7 Touch/Games/World of Warcraft/_classic_"
17:58:19.873 [ajour_core::fs::addon][DEBUG] To directory: "/Volumes/T7 Touch/Games/World of Warcraft/_classic_/Interface/AddOns"
17:58:19.873 [ajour_core::fs::addon][DEBUG] Zip path: "/Volumes/T7 Touch/Games/World of Warcraft/_classic_/5251166554282412174"
17:58:19.873 [ajour_core::fs::addon][DEBUG] File opened
17:58:19.887 [ajour_core::fs::addon][DEBUG] Zip opened
17:58:19.887 [ajour_core::fs::addon][DEBUG] Existing folders purged 1/2
17:58:19.889 [ajour_core::fs::addon][DEBUG] Existing folders purged 2/2
17:58:19.889 [ajour_core::fs::addon][DEBUG] Creating directory: "/Volumes/T7 Touch/Games/World of Warcraft/_classic_/Interface/AddOns/ElvUI_OptionsUI"
17:58:19.889 [ajour_core::fs::addon][DEBUG] Directory created: "/Volumes/T7 Touch/Games/World of Warcraft/_classic_/Interface/AddOns/ElvUI_OptionsUI"
`

**Comment by watsontom100** [comment]
Looked at the permissions of the folders, and if I compare it with the Details folder above this is what I get:

```
drwxrwxrwx  Details
drwxrwxrwx@ ElvUI
```

Not sure if the @ makes a difference in this case?

**Comment by tarkah** [comment]
Can you use `ls -@` to see the extended permissions for those folders?

**Comment by tarkah** [comment]
See https://apple.stackexchange.com/a/42178. I'd try to remove those permissions, I suspect that'll fix things.

**Comment by watsontom100** [comment]
Got it! Okay, that answer didn't work, because I think the issue was extended attributes rather than ACLs. But it provided a good lead and so instead I tried `xattr -rc ElvUI` as well as `xattr -rc ElvUI_OptionsUI` which clears the extended attributes on the folder and recursively on each file/ folder within it as well. 

The issue seems to be something to do with how Apple adds `com.apple.metadata._kMDItemUserTags` to files for it's tags features. Who knows why this only affected ElvUI mind?!

**Comment by tarkah** [comment]
Yeah, that's so odd. Awesome you got it resolved!
