### ISSUE TITLE
Implement a higher-contrast light theme

### ISSUE THREAD

**Issue by Maia-Everett** [ajour/ajour#656]
**Is your feature request related to a problem? Please describe.**
I prefer light UI themes, but Ajour provides very few light themes, and those it does provide are pretty low-contrast. In particular, the "Light" theme uses too light a shade of grey for main text and too bright a shade of purplish-blue for links.

**Describe the solution you'd like**
I would like a light theme with a contrast level similar to GitHub's light theme: either very dark grey text on a white background, or black text on a light grey background.

**Describe alternatives you've considered**
As a workaround, I have built a custom light theme with higher contrast than the default, but I have multiple installations of WoW (and Ajour), and it will be inconvenient to replicate this setting across each and every one of them.

**Comment by casperstorm** [comment]
Thanks for the suggestion, @Maia-Everett.
I would happily include a high(er)-contrast light theme. If you already have made one you could submit it here, or share it through our [theme editor](http://theme.getajour.com/).
