### ISSUE TITLE
[Feature] Deleting SavedVariables on-demand for individual addons

### ISSUE THREAD

**Issue by Bananaman** [ajour/ajour#658]
It's very frustrating to delete orphaned SavedVariables manually, or when doing it manually to reset specific addon settings.

Ajour has a "delete SavedVariables when uninstalling" feature but it's too heavy-handed, because I could forget that it's on and just delete/re-install something and lose all my settings.

I propose a secondary feature:

1. Click on an addon in My Library.
2. In the expanded view with "Exclude", "Delete" etc, have a "Wipe SavedVariables" button.
3. Clicking the button must bring up a dialog "Are you sure you want to delete all settings for addon X?" Yes/No, to avoid accidents.

This was the *single nice feature* I saw during my brief use of CurseForge. Their client has a right-click "Delete SavedVariables" menu entry and it was super useful.

**Comment by casperstorm** [comment]
Released in [1.2.3-rc.1](https://github.com/ajour/ajour/releases/tag/1.2.3-rc.1).
