### ISSUE TITLE
Townlog yak's API is unavailable anymore, workarounds need code

### ISSUE THREAD

**Issue by tebowy** [ajour/ajour#662]
Townlong yak has shut down their update API. Which means addons that got update in the meantime (ie. Venture Plan) don't show up as outdated in ajour.

Would it be possible to scrape their page locally to update the addons?

**Describe alternatives you've considered**
Only downloading mods manually from them.

**Additional context**
I don't know why they've closed their API.

**Comment by tarkah** [comment]
We do not plan on supporting TownlongYak in it's current form. The maintainer has not given any clear indication that they will publish a new API.

We do not plan on creating workarounds to "scrape" their website and only want to support sources that have stable and reliable APIs.

**Comment by tebowy** [comment]
API seems up again?

**Comment by casperstorm** [comment]
> API seems up again?

Yes, so that's nice for everyone using his addons!
