### ISSUE TITLE
Wardrobe Enhanced addon not available in catalogue

### ISSUE THREAD

**Issue by Walkerbo** [ajour/ajour#663]
_Describe the bug_
The Wardrobe Enhanced addon does not show in the catalogue

_Steps to reproduce the behaviour:_
1.Select Retail
2. Click on Catalogue
3. Select Curse from source dropdown
4. Type in wardrobe

_Expected behavior_
I expect to see a listing and link to the curse Wardrobe Enhanced file/website
https://www.curseforge.com/wow/addons/wardrobe-enhanced

**Comment by casperstorm** [comment]
<img width="961" alt="Screenshot 2021-06-26 at 18 49 30" src="https://user-images.githubusercontent.com/2248455/123520081-44fd3d80-d6af-11eb-962d-2b8b7df99280.png">

Isn't it this one?

**Comment by Walkerbo** [comment]
Yes, that is the one; I can now see it.

I am going to suggest that this is a case of PEBCAK.

Cheers
