### ISSUE TITLE
updated gpu driver not it not launching

### ISSUE THREAD

**Issue by hasnogaems** [ajour/ajour#669]
Check this: 16:20:15.480 [panic][ERROR] thread 'main' panicked at 'running Ajour gui: GraphicsAdapterNotFound': src\gui
ajour.log

> 16:20:14.322 [ajour][INFO] Ajour 1.2.0 has started.
> 16:20:14.325 [ajour::gui][DEBUG] config loaded:
> Config {
>     wow: Wow {
>         directory: None,
>         directories: {
>             ClassicTbc: "G:\\games\\World of Warcraft\\_classic_",
>             Retail: "E:\\Games\\NEW D\\Wow Farm\\World of Warcraft\\_retail_",
>             ClassicEra: "G:\\games\\World of Warcraft\\_classic_era_",
>             RetailPtr: "E:\\Games\\NEW D\\Wow Farm\\World of Warcraft\\_ptr_",
>         },
>         flavor: Retail,
>     },
>     addons: Addons {
>         global_release_channel: Stable,
>         ignored: {
>             RetailPtr: [],
>             ClassicTbc: [
>                 "TradeSkillMaster",
>             ],
>             ClassicEra: [],
>             Retail: [],
>         },
>         release_channels: {
>             ClassicEra: {},
>             Retail: {},
>             ClassicTbc: {},
>             RetailPtr: {},
>         },
>         delete_saved_variables: false,
>     },
>     theme: None,
>     column_config: V1 {
>         local_version_width: 150,
>         remote_version_width: 150,
>         status_width: 85,
>     },
>     window_size: Some(
>         (
>             1088,
>             788,
>         ),
>     ),
>     scale: None,
>     backup_directory: Some(
>         "E:\\Games\\NEW D\\Wow Farm\\World of Warcraft",
>     ),
>     backup_addons: true,
>     backup_wtf: true,
>     backup_config: false,
>     hide_ignored_addons: false,
>     self_update_channel: Stable,
>     weak_auras_account: {},
>     alternating_row_colors: false,
>     language: English,
>     catalog_source: Some(
>         Curse,
>     ),
>     auto_update: false,
>     compression_format: Zip,
>     close_to_tray: true,
>     autostart: false,
>     start_closed_to_tray: false,
> }
> 16:20:14.326 [ajour::gui][DEBUG] antialiasing: true
> 16:20:15.480 [panic][ERROR] thread 'main' panicked at 'running Ajour gui: GraphicsAdapterNotFound': src\gui\mod.rs:1172
>    0: <unknown>
>    1: <unknown>
>    2: <unknown>
>    3: <unknown>
>    4: <unknown>
>    5: <unknown>
>    6: <unknown>
>    7: <unknown>
>    8: <unknown>
>    9: <unknown>
>   10: <unknown>
>   11: <unknown>
>   12: <unknown>
>   13: <unknown>
>   14: <unknown>
>   15: <unknown>
>   16: BaseThreadInitThunk
>   17: RtlUserThreadStart
>

**Comment by casperstorm** [comment]
Have you tried the OpenGL version of Ajour? You can find it here: https://www.getajour.com/download.

**Comment by hasnogaems** [comment]
@casperstorm Yes, it worked! Thank you so much for blazing fast response good sir. Your manager rocks! I would only ask for auto backup wtf/inreface feature.
