### ISSUE TITLE
Is it possible to add the backup Fonts feature？

### ISSUE THREAD

**Issue by Sooongz** [ajour/ajour#675]
Just like backup the Addons and WTF directory, Whether the custom Fonts directory can also support the backup?

![image](https://user-images.githubusercontent.com/1811858/124714498-6f16f100-df34-11eb-890a-7457a6f9b834.png)

**Comment by casperstorm** [comment]
Could you elaborate a little on this feature request, @Sooongz?

**Comment by casperstorm** [comment]
This will be added once #684 is reviewed and merged. Thanks for suggestion a feature.

**Comment by casperstorm** [comment]
Released in [1.2.3-rc.1](https://github.com/ajour/ajour/releases/tag/1.2.3-rc.1).
Make sure to set Ajour Update Channel to Beta in order download this pre-release.
