### ISSUE TITLE
[Bug] TBC Addon installed from Curse gets matched to Retail version from WowInterface

### ISSUE THREAD

**Issue by Bananaman** [ajour/ajour#676]
1. Install "Fishing Buddy (Classic)" from Curse Catalog
2. Refresh addons.
3. Ajour shows a Retail update from WowInterface, which breaks the addon if you install it... 😁

![image](https://user-images.githubusercontent.com/38923130/124810448-a354d680-df61-11eb-9f36-63c0f166ea19.png)

**Comment by JoshStrobl** [comment]
Duplicate of #664

**Comment by casperstorm** [comment]
Gonna continue this in #664, as @JoshStrobl points out.

**Comment by Bananaman** [comment]
Weird, I read through open issues and did not see that one. Sorry. 🤔
