### ISSUE TITLE
Excessive Size of target Directory after a build (1.34 Gb)

### ISSUE THREAD

**Issue by oscassey** [ajour/ajour#679]
**Describe the bug**
Once built, the target directory has a size of 1.34 Gb for an executable of 20 Mb. Why so much space?

**To Reproduce**
1. Windows 10, cygwin, git, rust, cargo, make
2. git pull
3. make
4. Calculate the size of the target directory

**Expected behavior**
It seems excessive for the complexity of the application to need 1.34 Gb of dependencies.

**Screenshots**
![image](https://user-images.githubusercontent.com/77948969/125286844-3edfa180-e2ea-11eb-8ad8-6b0e135427cf.png)

**Software involved**
Please complete the following information:
 - OS: "Windows 10"
 - Ajour version: commit acee40b7e6ab4dd73274ad3c217737919d3a8907 (HEAD -> master, tag: 1.2.2, origin/master, origin/development, origin/HEAD)
 - (if applicable) Addon name, flavor (classic or retail) and version: n/a

**Additional context**

**Log Output**
Paste the content of `ajour.log` from `%APPDATA%\ajour\ajour.log` on Windows or `$HOME/.config/ajour/ajour.log` on Mac/Linux.

n/a

**Comment by casperstorm** [comment]
This is mainly because of build artifacts. You can take a look at [cargo-sweep](https://github.com/holmgr/cargo-sweep) which can remove unused files.

Since this issue is not really related to Ajour, I'll close it again.

**Comment by oscassey** [comment]
How come ajour needs 1.34 Gb of build artefacts for its 20 Mb size?

**Comment by casperstorm** [comment]
> How come ajour needs 1.34 Gb of build artefacts for its 20 Mb size?

It is common for any Rust project. We are not in control.
