### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by Nelfym** [ajour/ajour#680]
_Edit: Oops, wrong label? Sorry._

Hello.

**Describe the bug**
Just spotted some untranslated strings.
- whole tray menu
![image](https://user-images.githubusercontent.com/12660094/125322931-90b21700-e33e-11eb-9dc8-045edd0c0cc8.png)

- in settings, field where we can put an URL to import a theme
![image](https://user-images.githubusercontent.com/12660094/125322972-9a3b7f00-e33e-11eb-89a9-9331c7d86ff7.png)

That's all.
Cheers.

**Comment by casperstorm** [comment]
Released in [1.2.3-rc.1](https://github.com/ajour/ajour/releases/tag/1.2.3-rc.1).
