### ISSUE TITLE
Trying to search Gladdy in catalog

### ISSUE THREAD

**Issue by hasnogaems** [ajour/ajour#697]
Not finding anything but actually present at curseforge https://www.curseforge.com/wow/addons/gladdy-tbc
Im using last open gl version 1.2.3

**Comment by casperstorm** [comment]
Thank you for reporting this error. I've fixed the issue so you can re-launch Ajour and you should be able to see it!

Problem was that while building the Catalog we were only looking for stable releases on a CurseForge addon, however, there have only been published beta releases to Gladdy. We are now looking for both stable and beta releases (https://github.com/ajour/catalog/commit/938ce11038c68ae122920bfe6d5ab31c9dd3677c)

<img width="861" alt="Screenshot 2021-07-23 at 15 19 45" src="https://user-images.githubusercontent.com/2248455/126787568-2711a8e2-df92-4ea7-971e-cee7b41d7ce5.png">

**Comment by hasnogaems** [comment]
amazing!

**Comment by hasnogaems** [comment]
How you responding  so fast? You have some github client or something?

**Comment by casperstorm** [comment]
> How you responding so fast? You have some github client or something?

We have a Github webhook on our [Discord server](https://discord.gg/4838t9R). I get notifications on my phone from that hook and I just happened to have time to fix it right away 😊
