### ISSUE TITLE
Catalog Version Filter

### ISSUE THREAD

**Issue by Industrial** [ajour/ajour#702]
**Is your feature request related to a problem? Please describe.**
I can't filter addons in the Catalog by wow version.

**Describe the solution you'd like**
Add a filter between Category and #results

**Describe alternatives you've considered**
Sort by game version

**Comment by casperstorm** [comment]
We have had this requested before (see: https://github.com/ajour/ajour/issues/541).
My view on this is currently the same:

> While the Catalog is great and fast for installing addons, it's never been the intention to be a place to go if you are on the lookout for new and addons, without knowing exactly what you want. There are better alternatives for that, with images, videos, and such. I believe, as @mlablah points out, the right solution here is to use our columns to display Game Versions.
>
> Honestly, I am even questioning us having a filter for categories. I don't think it is very used.

From: https://github.com/ajour/ajour/issues/541#issuecomment-879832778
