### ISSUE TITLE
Allow completely disabling update checking for those who use a package manager

### ISSUE THREAD

**Issue by StrangePeanut** [ajour/ajour#704]
**Is your feature request related to a problem? Please describe.**
Using a package manager the update button continue to shows up and an accidental click causes the program to update itself rather than through the package manager

**Describe the solution you'd like**
There should be an option to completely disable update checks so that the update button does not show up at all

**Additional context**
Besides browsers and game clients every single program on my PC has the option to fully disable auto updates. For this reason I believe this is a reasonable request to have implemented not to mention it would take very little effort.

That being said thanks so much for this amazing addon manager!!

**Comment by mlablah** [comment]
On linux machines Ajour won't show the option to update itself, if it sees it's not running inside an AppImage (as would often be the case if someone built Ajour from source).

If whether or not to check for updates is added as a setting, we should be mindful of this logic:
https://github.com/ajour/ajour/blob/master/src/gui/element/menu.rs#L300-L310

**Comment by JoshStrobl** [comment]
> On linux machines Ajour won't show the option to update itself

This is not correct. It does in fact show a notification that there is a new update for it outside the AppImage. Maybe this is an unintended bug.

I would also like to see this as a compilation option for Ajour if possible. I am the package maintainer of Ajour on Solus and while I appreciate it notifying users of a new update, we perform weekly syncs to our stable repo every Friday and thus users would keep seeing that notification until the next sync in scenarios where I can't directly "cherrypick" that ajour update from our unstable to the stable repos, e.g. in situations where we have other major changes happening.

**Comment by StrangePeanut** [comment]
Just want to add Ajour is also actively maintained on Chocolatey for Windows.

Not sure about BSD but including an option to completely disable the check would serve everybody with the issue equally well regardless of the currently existing logic.

**Comment by mlablah** [comment]
> This is not correct. It does in fact show a notification that there is a new update for it outside the AppImage. Maybe this is an unintended bug.

I didn't phrase that right. Ajour doesn't show the update button in that scenario (since the selfupdate flow wouldn't work correctly). It still presents that information that there is a new version available.

Sorry for the confusion.

**Comment by casperstorm** [comment]
We could make it an option for specific assets by writing a boolean value to `ajour.yml,` but if we want a non-updatable Windows (or Mac) version, we should make a new asset, I guess?

**Comment by tarkah** [comment]
Here is where we check for the latest release...

https://github.com/ajour/ajour/blob/788d55f3c0b89a0c7b757799cbbf3eedbc2b08ed/crates/core/src/utility.rs#L61-L83

I'm thinking the best way to handle this is adding a new feature called `no-self-update`, which can be passed during compilation... `cargo build --features no-self-update ...`. If that feature is active, we just return `None` here, which will completely kills any self update functionality. I can add this.

@StrangePeanut As for Chocolately, it appears the install script just grabs the release asset from Github. In this case, we'd either need to publish a separate executable (with the feature active) that can be downloaded, or we can the script updated to create an empty `no-update` file in `%APPDATA%\ajour`, which we can add a check on startup to disable self updating. Probably just easiest to publish a new `no-self-update` binary.

**Comment by mlablah** [comment]
so users would have to download a different asset to enable or disable self-updating?

**Comment by tarkah** [comment]
This wouldn't be an asset we add to the website and I don't think it'd be something normal users would manually download. It's really only intended for packaging. We can add a note about it to install instructions for packagers.
