### ISSUE TITLE
Auto backup?

### ISSUE THREAD

**Issue by hasnogaems** [ajour/ajour#707]
Would be so nice to have scheduled backup.

**Comment by mryanlam** [comment]
Should be able to do a back up in cronjob like

0 */3 * * * /Applications/Ajour.app/Contents/MacOS/ajour backup

**Comment by JoshStrobl** [comment]
Copying my remarks from Discord here.

---

Providing an automated backup solution in Ajour itself would only add unnecessary complexity to the software. First off, you would need implement either an ajour service on Windows, setup autostart on Linux (typically copying the desktop file into the proper XDG DATA DIR), and whatever devilry macOS has. Personally, I can't stand applications which default to adding itself to autostart after its first launch, however the only other alternative would be (at least on LInux) shipping a systemd unit that the user needs to enable as themselves, alongside a timer to ensure the service is run as specific calendar times. These would still need to be enabled by the user.

Once it starts doing backups, what decides how many backups persist in the Ajour Backups folder? Is it done on a daily basis? Weekly? Monthly? Last day for each week being stored for N weeks? For each addon? What about when an addon is installed or removed? These are all backup retention policies. Ajour shouldn't need to handle that either. If it did, it'd need to keep track of backups, likely need to communicate versioning information / what is in each backup, etc.

Those backups would likely still only be in that directory. So what about remote backup solutions? Or samba / network mounts? xyz esoteric solution like "restic + rsync.net" that I use, which has its own custom retention policies? Even more needless work that wouldn't provide 100% coverage of all the backup solutions on the market. Not to mention that with how Ajour does backups, which is taking a snapshot and saving it as a date + time ZIP or tarball, some solutions like Nextcloud which version specific files would end up retaining old versions of old files unintentionally.

The safest best is IMO is having ajour do what it already does and leaving the rest up to the user. Can't help if the user doesn't perform backups, having good backup practices is just common sense in the current era of computing, especially when some operating systems like macOS and Windows already come with their own solutions (iCloud and OneDrive respectively).

**Comment by casperstorm** [comment]
I was actually just about to copy your response, @JoshStrobl. It perfectly reflects our vision.
For a scheduled backup, it is possible to do by using CLI as @mryanlam suggests.

More information about the possibility of backup using CLI can be found [here](https://github.com/ajour/ajour/blob/master/CLI.md#backup) and you can also find some examples using CLI in our [Wiki](https://github.com/ajour/ajour/wiki/Update-addons-automatically-when-you-log-in-(Windows)).

**Comment by hasnogaems** [comment]
What I talking about is just press backup button automatically once in a while so I dont need to press it manually. Without autorun, without any fancyness. As simple and minimalistic as possible.
