### ISSUE TITLE
Catches Tab before windows focus

### ISSUE THREAD

**Issue by jimnordb** [ajour/ajour#731]
**Describe the bug**
Too early key event detection

**To Reproduce**
Open Ajour and then put it in the background. Then Alt-Tab into Ajour and it will change view

**Expected behavior**
Should not listen to Tab keyevent before window is focused.

**Software involved**
 - OS: Windows 21H1
 - Ajour version:  1.3.0

**Comment by casperstorm** [comment]
Will be fixed in #732!
