### ISSUE TITLE
macOS Monterey 12.0.1 crash

### ISSUE THREAD

**Issue by Sooongz** [ajour/ajour#743]
Crash when open ajour

This is the log

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               ajour [24862]
Path:                  /Applications/Ajour.app/Contents/MacOS/ajour
Identifier:            com.rogildstorm.ajour
Version:               1.0.0 (1)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2021-10-28 12:31:56.7404 +0800
OS Version:            macOS 12.0.1 (21A559)
Report Version:        12
Anonymous UUID:        2C82DBEE-1EA1-D3F8-27FB-D39DA5FCDC75

Sleep/Wake UUID:       3591FA9C-B17C-455A-A0E5-C1836E532C07

Time Awake Since Boot: 150000 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 9 
rebase opcodes terminated early at offset 1 of 13672

Application Specific Information:
rebase opcodes terminated early at offset 1 of 13672

Thread 0 Crashed:
0   dyld                          	       0x118d6d0ce __abort_with_payload + 10
1   dyld                          	       0x118d831cf abort_with_payload_wrapper_internal + 80
2   dyld                          	       0x118d83201 abort_with_payload + 9
3   dyld                          	       0x118d31613 dyld4::halt(char const*) + 375
4   dyld                          	       0x118d2d55d dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3955
5   dyld                          	       0x118d2c4b4 start + 388

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7b5bc7eb8  rdx: 0x00007ff7b5bc8320
  rdi: 0x0000000000000006  rsi: 0x0000000000000009  rbp: 0x00007ff7b5bc7f00  rsp: 0x00007ff7b5bc7eb8
   r8: 0x00007ff7b5bc7f20   r9: 0x0000000000000000  r10: 0x0000000000000014  r11: 0x0000000000000246
  r12: 0x0000000000000014  r13: 0x00007ff7b5bc8320  r14: 0x0000000000000009  r15: 0x0000000000000006
  rip: 0x0000000118d6d0ce  rfl: 0x0000000000000246  cr2: 0x000000010b2e2000
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133

Binary Images:
       0x118d27000 -        0x118d92fff dyld (*) <1a6ae033-9438-33c0-8077-988fd885250a> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 1563
    thread_create: 0
    thread_set_state: 1030

VM Region Summary:
ReadOnly portion of Libraries: Total=830.1M resident=0K(0%) swapped_out_or_unallocated=830.1M(100%)
Writable regions: Total=9220K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9220K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                         12K        3 
__DATA                            16.1M      234 
__DATA_CONST                      10.8M      142 
__DATA_DIRTY                       484K       84 
__FONT_DATA                          4K        1 
__LINKEDIT                       638.9M        7 
__OBJC_RO                         81.5M        1 
__OBJC_RW                         3120K        1 
__TEXT                           191.2M      249 
__UNICODE                          588K        1 
dyld private memory               1024K        1 
===========                     =======  ======= 
TOTAL                              1.0G      726 

-----------
Full Report
-----------

{"app_name":"ajour","timestamp":"2021-10-28 12:31:56.00 +0800","app_version":"1.0.0","slice_uuid":"2bc7119b-54c5-346d-a495-c3a69ddfc9ca","build_version":"1","platform":1,"bundleID":"com.rogildstorm.ajour","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.0.1 (21A559)","incident_id":"71A1DEDF-7818-4326-8E0C-67A3016F9034","name":"ajour"}
{
  "uptime" : 150000,
  "procLaunch" : "2021-10-28 12:31:56.7167 +0800",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iMac17,1",
  "procStartAbsTime" : 152486053662308,
  "coalitionID" : 20330,
  "osVersion" : {
    "train" : "macOS 12.0.1",
    "build" : "21A559",
    "releaseType" : "User"
  },
  "captureTime" : "2021-10-28 12:31:56.7404 +0800",
  "incident" : "71A1DEDF-7818-4326-8E0C-67A3016F9034",
  "bug_type" : "309",
  "pid" : 24862,
  "procExitAbsTime" : 152486072716835,
  "cpuType" : "X86-64",
  "procName" : "ajour",
  "procPath" : "\/Applications\/Ajour.app\/Contents\/MacOS\/ajour",
  "bundleInfo" : {"CFBundleShortVersionString":"1.0.0","CFBundleVersion":"1","CFBundleIdentifier":"com.rogildstorm.ajour"},
  "storeInfo" : {"deviceIdentifierForVendor":"4AB877BB-88CD-5063-8DF4-4BEFA8746F4C","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.rogildstorm.ajour",
  "crashReporterKey" : "2C82DBEE-1EA1-D3F8-27FB-D39DA5FCDC75",
  "sleepWakeUUID" : "3591FA9C-B17C-455A-A0E5-C1836E532C07",
  "sip" : "disabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":9,"flags":518,"namespace":"DYLD","reasons":["rebase opcodes terminated early at offset 1 of 13672"]},
  "asi" : {"dyld":["rebase opcodes terminated early at offset 1 of 13672"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":1030,"task_for_pid":1563},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":1712640,"threadState":{"r13":{"value":140701882680096},"rax":{"value":33554953},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":9},"rsi":{"value":9},"r8":{"value":140701882679072},"cr2":{"value":4482539520},"rdx":{"value":140701882680096},"r10":{"value":20},"r9":{"value":0},"r15":{"value":6},"rbx":{"value":0},"trap":{"value":133},"err":{"value":33554953},"r11":{"value":582},"rip":{"value":4711698638,"matchesCrashFrame":1},"rbp":{"value":140701882679040},"rsp":{"value":140701882678968},"r12":{"value":20},"rcx":{"value":140701882678968},"flavor":"x86_THREAD_STATE","rdi":{"value":6}},"frames":[{"imageOffset":286926,"symbol":"__abort_with_payload","symbolLocation":10,"imageIndex":0},{"imageOffset":377295,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":377345,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":0},{"imageOffset":42515,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":0},{"imageOffset":25949,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3955,"imageIndex":0},{"imageOffset":21684,"symbol":"start","symbolLocation":388,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4711411712,
    "size" : 442368,
    "uuid" : "1a6ae033-9438-33c0-8077-988fd885250a",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 140703306563584,
  "size" : 15213641728,
  "uuid" : "3d05845f-3f65-358f-9ebf-2236e772ac01"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=830.1M resident=0K(0%) swapped_out_or_unallocated=830.1M(100%)\nWritable regions: Total=9220K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9220K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                         12K        3 \n__DATA                            16.1M      234 \n__DATA_CONST                      10.8M      142 \n__DATA_DIRTY                       484K       84 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       638.9M        7 \n__OBJC_RO                         81.5M        1 \n__OBJC_RW                         3120K        1 \n__TEXT                           191.2M      249 \n__UNICODE                          588K        1 \ndyld private memory               1024K        1 \n===========                     =======  ======= \nTOTAL                              1.0G      726 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "61704e71b6f6b8421579caf8"
      },
      "deploymentId" : 240000293
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000145
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000064
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "6169fcad436117010456880e"
      },
      "deploymentId" : 240000238
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    }
  ],
  "experiments" : [

  ]
}
}

**Comment by AngelOnFira** [comment]
It appears that you're using version 1.0.0 of Ajour? I just compiled/ran Ajour from the master branch, and it seems fine on my M1 Air/Monterey 12.0.1.

**Comment by Sooongz** [comment]
Version 1.3.2 Intel i5
After reinstallation, it's ok
